<template><AppLayout><div class="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-6 lg:p-8">
<header class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-primary-600">Reliability Control</p><h1 class="mt-1 text-3xl font-bold">赔付 Shadow</h1><p class="mt-2 text-sm text-gray-500">只生成不可变草案和修订；不会写余额、Builder Pass、通知或邮件。</p></div><label class="text-sm"><input v-model="enabled" type="checkbox"/> 开启 Shadow 草案 <button :disabled="acting" class="ml-2 rounded-xl bg-primary-600 px-4 py-2 text-white disabled:opacity-50" @click="save">保存</button></label></header>
<div v-if="error" role="alert" class="rounded-xl bg-danger-50 p-4 text-danger-700">{{error}}</div>
<section v-if="snapshot" class="grid gap-3 sm:grid-cols-4"><Metric label="Shadow 天数" :value="`${snapshot.assessment.elapsed_days} / ${snapshot.assessment.minimum_days}`"/><Metric label="Incident / 已复核" :value="`${snapshot.assessment.evaluated_incident_count} / ${snapshot.assessment.reviewed_incident_count}`"/><Metric label="Owner 复核资格" :value="snapshot.assessment.eligible_for_owner_review?'已满足':'未满足'"/><Metric label="执行通道" value="不存在（PR8）"/></section>
<section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800"><div class="flex gap-2"><input v-model.number="incidentId" aria-label="Incident ID" type="number" min="1" class="rounded-xl border px-3 py-2 dark:bg-dark-900" placeholder="Incident ID"/><button :disabled="acting||!incidentId" class="rounded-xl border px-4 py-2" @click="generate">生成/读取草案</button></div></section>
<section v-if="snapshot" class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800"><table class="min-w-full text-sm"><thead><tr><th>Incident</th><th>Revision</th><th>用户</th><th>拟赔</th><th>高价值门禁</th><th>Evidence</th></tr></thead><tbody><tr v-for="draft in snapshot.drafts" :key="draft.id" data-test="draft-row" class="cursor-pointer border-t" @click="selectDraft(draft.id)"><td>#{{draft.incident_id}}</td><td>R{{draft.revision_number}}</td><td>{{draft.eligible_user_count}} / {{draft.affected_user_count}}</td><td>{{money(draft.proposed_total_cny_fen)}}</td><td>{{draft.high_value?'必须重新设计':'Shadow'}}</td><td class="max-w-48 truncate">{{draft.evidence_hash}}</td></tr><tr v-if="!snapshot.drafts.length"><td colspan="6" class="p-8 text-center text-gray-500">尚无 Shadow 草案</td></tr></tbody></table></section>
<section v-if="draft" class="space-y-4"><article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800"><h2 class="text-xl font-bold">Incident #{{draft.incident_id}} · Revision {{draft.revision_number}}</h2><p class="mt-2 text-sm" :class="draft.high_value?'text-danger-600':'text-gray-500'">{{draft.high_value?`总额跨过 ${money(draft.high_value_threshold_cny_fen)}，本版本不可原样批准，必须创建更低的新修订。`:'仅供 Shadow 比较，不可执行。'}}</p><p class="mt-2 break-all text-xs text-gray-500">Evidence {{draft.evidence_hash}}</p></article>
<article v-for="user in draft.users" :key="user.user_id" class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800"><div class="flex justify-between"><h3 class="font-bold">{{user.email||`User #${user.user_id}`}} · {{user.eligible?'符合资格':'不符合资格'}}</h3><strong>{{money(user.proposed_total_cny_fen)}}</strong></div><p class="mt-1 text-sm text-gray-500">最终失败 {{user.final_failure_count}} 次 · {{user.exclusion_reason||`限制项 ${user.limiting_cap}`}} · 余额 {{money(user.balance_benefit_cny_fen)}} · Builder Pass {{money(user.builder_pass_benefit_cny_fen)}}</p><table class="mt-3 min-w-full text-xs"><thead><tr><th>服务 / 分组</th><th>时长</th><th>公式参数</th><th>原始值</th><th>分配</th></tr></thead><tbody><tr v-for="item in user.items" :key="item.id" class="border-t"><td>{{item.product_name}} / {{item.group_name||'缺少分组'}}<span class="block text-warning-600">{{item.exclusion_reason}}</span></td><td>{{duration(item.compensable_duration_ms)}}</td><td>¥{{(item.product_rate_cny_fen_per_hour/100).toFixed(2)}}/h × {{(item.group_weight_bps/10000).toFixed(2)}} × {{(item.tier_multiplier_bps/10000).toFixed(2)}}</td><td>{{micros(item.raw_value_cny_micros)}}</td><td>{{money(item.proposed_cny_fen)}} → {{item.benefit_channel==='builder_pass'?'Builder Pass':'余额'}}</td></tr></tbody></table></article>
<article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800"><h3 class="font-bold">记录 Shadow 对比</h3><div v-if="draft.review" class="mt-2 text-sm">Owner 判断 {{money(draft.review.owner_judgement_total_cny_fen)}} · 差异 {{money(draft.review.variance_cny_fen)}} · {{draft.review.result}}<p class="text-gray-500">{{draft.review.notes}}</p></div><div v-else class="mt-3 grid gap-2"><input v-model.number="reviewAmount" aria-label="Owner 判断金额" type="number" min="0" class="rounded-xl border px-3 py-2 dark:bg-dark-900"/><select v-model="reviewResult" aria-label="复核结果" class="rounded-xl border px-3 py-2 dark:bg-dark-900"><option value="aligned">符合判断</option><option value="redesign_required">需要重新设计</option></select><input v-model="reviewNotes" aria-label="复核说明" class="rounded-xl border px-3 py-2 dark:bg-dark-900" placeholder="比较依据"/><button :disabled="acting||!reviewNotes" class="rounded-xl border px-4 py-2" @click="review">保存不可变复核</button></div></article>
<article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800"><h3 class="font-bold">创建不可变修订</h3><p class="mt-1 text-xs text-gray-500">高价值草案不能自动缩放；请输入理由并逐用户重设金额，生成保留 before/after 的新版本。</p><input v-model="revisionReason" aria-label="修订原因" class="mt-3 w-full rounded-xl border px-3 py-2 dark:bg-dark-900" placeholder="必填原因"/><div v-for="user in draft.users" :key="`adjust-${user.user_id}`" class="mt-2 flex items-center gap-2"><label><input v-model="revisionIncluded[user.user_id]" type="checkbox"/> User #{{user.user_id}}</label><input v-model.number="revisionAmounts[user.user_id]" :aria-label="`User ${user.user_id} 修订金额`" type="number" min="0" class="rounded-xl border px-3 py-2 dark:bg-dark-900"/> 分</div><button :disabled="acting||!revisionReason" class="mt-3 rounded-xl bg-warning-600 px-4 py-2 text-white disabled:opacity-50" @click="revise">创建新 Revision</button></article></section>
</div></AppLayout></template>
<script setup lang="ts">
import {defineComponent,h,onBeforeUnmount,onMounted,ref} from 'vue';import AppLayout from '@/components/layout/AppLayout.vue';import {generateCompensationDraft,getCompensationDraft,getCompensationSnapshot,reviseCompensationDraft,reviewCompensationDraft,updateCompensationShadow,type CompensationDraft,type CompensationSnapshot} from '@/api/admin/compensation'
const Metric=defineComponent({props:{label:String,value:String},setup:p=>()=>h('div',{class:'rounded-2xl bg-white p-4 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800'},[h('span',{class:'text-xs text-gray-500'},p.label),h('strong',{class:'mt-1 block'},p.value)])});const snapshot=ref<CompensationSnapshot|null>(null),draft=ref<CompensationDraft|null>(null),enabled=ref(false),error=ref(''),acting=ref(false),incidentId=ref<number>(),revisionReason=ref(''),revisionAmounts=ref<Record<number,number>>({}),revisionIncluded=ref<Record<number,boolean>>({}),reviewAmount=ref(0),reviewResult=ref('aligned'),reviewNotes=ref('');let stopped=false,listController:AbortController|null=null,detailController:AbortController|null=null,listRequest=0,detailRequest=0
async function load(){if(stopped)return;listController?.abort();const controller=new AbortController();listController=controller;const request=++listRequest;try{const next=await getCompensationSnapshot(controller.signal);if(stopped||controller.signal.aborted||request!==listRequest)return;snapshot.value=next;enabled.value=next.enabled}catch(cause){if(!stopped&&!controller.signal.aborted&&request===listRequest)error.value=cause instanceof Error?cause.message:'加载失败'}}
async function selectDraft(id:number){if(stopped)return;detailController?.abort();const controller=new AbortController();detailController=controller;const request=++detailRequest;try{const next=await getCompensationDraft(id,controller.signal);if(stopped||controller.signal.aborted||request!==detailRequest)return;draft.value=next;revisionAmounts.value={};revisionIncluded.value={};for(const user of next.users||[]){revisionAmounts.value[user.user_id]=user.proposed_total_cny_fen;revisionIncluded.value[user.user_id]=user.included}reviewAmount.value=next.proposed_total_cny_fen;reviewResult.value=next.high_value?'redesign_required':'aligned';reviewNotes.value=''}catch(cause){if(!stopped&&!controller.signal.aborted&&request===detailRequest)error.value=cause instanceof Error?cause.message:'草案加载失败'}}
async function act<T>(action:()=>Promise<T>,apply?:(value:T)=>void){if(stopped||acting.value)return;acting.value=true;try{const value=await action();if(stopped)return;apply?.(value);await load();if(stopped)return;if(draft.value)await selectDraft(draft.value.id)}catch(cause){if(!stopped)error.value=cause instanceof Error?cause.message:'操作失败'}finally{if(!stopped)acting.value=false}}
function save(){void act(()=>updateCompensationShadow(enabled.value))}function generate(){if(!incidentId.value)return;void act(()=>generateCompensationDraft(incidentId.value!),next=>{draft.value=next})}function revise(){if(!draft.value)return;const adjustments=(draft.value.users||[]).map(user=>({user_id:user.user_id,included:revisionIncluded.value[user.user_id]??false,proposed_cny_fen:revisionAmounts.value[user.user_id]??0}));void act(()=>reviseCompensationDraft(draft.value!.id,revisionReason.value,adjustments),next=>{draft.value=next})}function review(){if(!draft.value)return;void act(()=>reviewCompensationDraft(draft.value!.id,reviewAmount.value,reviewResult.value,reviewNotes.value))}function money(fen:number){return `¥${(fen/100).toFixed(2)}`}function micros(value:number){return `¥${(value/1_000_000).toFixed(6)}`}function duration(ms:number){return `${(ms/60_000).toFixed(1)} 分钟`}
onMounted(()=>{stopped=false;void load()});onBeforeUnmount(()=>{stopped=true;listController?.abort();detailController?.abort()})
</script>
