<template>
  <AppLayout>
    <div class="mx-auto max-w-[1400px] space-y-6 p-4 sm:p-6 lg:p-8">
      <header class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-primary-600">Reliability Control</p><h1 class="mt-1 text-3xl font-bold">客户等级</h1><p class="mt-2 text-sm text-gray-500">按滚动 90 天已核验现金收入计算；已使用付费额度仅作审计证据，不是人民币付款金额，等级不影响赔付资格。</p></div><div class="flex items-center gap-3"><label class="text-sm"><input v-model="enabled" type="checkbox" /> 每日评估</label><button :disabled="loading || acting" class="rounded-xl bg-primary-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" @click="saveSettings">保存并刷新</button></div></header>
      <div v-if="error" role="alert" class="rounded-2xl border border-danger-200 bg-danger-50 p-4 text-sm text-danger-700">{{ error }}</div>
      <section v-if="snapshot" class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800 dark:ring-dark-700"><div class="flex gap-2 p-3"><input v-model="search" aria-label="搜索客户" class="rounded-xl border px-3 py-2 dark:bg-dark-900" placeholder="邮箱或用户 ID" @keyup.enter="load(1)"/><button class="rounded-xl border px-3 py-2" @click="load(1)">搜索</button></div><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 text-xs text-gray-500 dark:bg-dark-900"><tr><th class="p-3">用户</th><th>当前等级</th><th title="已与用户和订单精确关联、扣除退款后的现金收入">90天已核验付款</th><th title="从付费余额批次或付费 Builder Pass 周期实际使用的额度，不是人民币付款金额">90天已使用付费额度</th><th>Grace / Override</th></tr></thead><tbody><tr v-for="customer in snapshot.customers" :key="customer.user_id" data-test="tier-row" class="cursor-pointer border-t dark:border-dark-700" @click="selectUser(customer.user_id)"><td class="p-3"><strong>{{ customer.email || `User #${customer.user_id}` }}</strong><span class="block text-xs text-gray-500">#{{ customer.user_id }}</span></td><td><span class="rounded-full border px-2 py-1 text-xs font-semibold">{{ tierLabel(customer.effective_tier) }}</span><span v-if="customer.calculated_tier !== customer.effective_tier" class="ml-2 text-xs text-warning-600">计算值 {{ tierLabel(customer.calculated_tier) }}</span></td><td>{{ formatCNY(customer.verified_paid_value_cny_fen) }}</td><td>{{ formatCredits(customer.verified_paid_consumption_micros) }}</td><td class="text-xs text-gray-500">{{ customer.projection_status ? 'Override 已过期，等待评估落库' : customer.override_id ? `Override #${customer.override_id}` : customer.grace_expires_at ? `Grace 至 ${formatTime(customer.grace_expires_at)}` : '—' }}</td></tr><tr v-if="!snapshot.customers.length"><td colspan="5" class="p-8 text-center text-gray-500">尚无客户等级评估。</td></tr></tbody></table><div class="flex items-center justify-between p-3 text-sm"><span>共 {{ snapshot.total }} 位</span><div class="flex gap-2"><button :disabled="snapshot.page <= 1" class="rounded-lg border px-3 py-1 disabled:opacity-50" @click="load(snapshot.page - 1)">上一页</button><button :disabled="snapshot.page * snapshot.page_size >= snapshot.total" class="rounded-lg border px-3 py-1 disabled:opacity-50" @click="load(snapshot.page + 1)">下一页</button></div></div></section>
      <section v-if="explanation" class="grid gap-5 xl:grid-cols-[1fr_1fr]">
        <article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800 dark:ring-dark-700"><h2 class="text-lg font-bold">{{ explanation.current.email || `User #${explanation.current.user_id}` }} · {{ tierLabel(explanation.current.effective_tier) }}</h2><div class="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="等级倍率" :value="`${explanation.benefit.multiplier}x`" /><Metric label="单次上限" :value="formatCNY(explanation.benefit.cap_cny_fen)" /><Metric label="已核验付款" :value="formatCNY(explanation.current.verified_paid_value_cny_fen)" /><Metric label="已使用付费额度" :value="formatCredits(explanation.current.verified_paid_consumption_micros)" /></div><p class="mt-3 text-xs text-gray-500">额度消耗，不等于人民币付款金额；客户等级只按已核验付款计算。</p><p class="mt-4 break-all text-xs text-gray-500">Evidence {{ explanation.evaluation.evidence_hash }}</p><h3 class="mt-5 font-semibold">不可变历史</h3><ol class="mt-2 space-y-2 text-sm"><li v-for="item in explanation.history" :key="item.id">{{ item.previous_tier ? tierLabel(item.previous_tier) : '首次评估' }} → {{ tierLabel(item.new_tier) }} · {{ item.change_reason }} · {{ formatTime(item.changed_at) }}</li></ol><h3 class="mt-5 font-semibold">Override 审计历史</h3><ol class="mt-2 space-y-2 text-sm"><li v-for="item in explanation.overrides" :key="item.id">{{ tierLabel(item.tier) }} · {{ item.reason }} · {{ formatTime(item.starts_at) }} 至 {{ formatTime(item.expires_at) }} · 操作者 #{{ item.created_by_user_id || 'system' }} · {{ item.refresh_status }} · 创建于 {{ formatTime(item.created_at) }}<span v-if="item.refresh_error" class="block text-danger-600">{{ item.refresh_error }}</span></li><li v-if="!explanation.overrides.length" class="text-gray-500">暂无 Override</li></ol></article>
        <article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-900/5 dark:bg-dark-800 dark:ring-dark-700"><h2 class="text-lg font-bold">付费来源与排除</h2><div class="mt-3 max-h-80 overflow-auto"><table class="min-w-full text-xs"><thead><tr><th class="text-left">来源</th><th>金额</th><th>结论</th></tr></thead><tbody><tr v-for="source in explanation.evaluation.evidence.paid_sources" :key="`${source.source_type}:${source.source_id}`" class="border-t dark:border-dark-700"><td class="py-2">{{ source.source_type }} #{{ source.source_id }}</td><td class="text-center">{{ formatCNY(source.amount_cny_fen) }}</td><td class="text-center" :class="source.included ? 'text-success-600' : 'text-warning-600'">{{ sourceConclusion(source.included, source.exclusion_reason) }}</td></tr></tbody></table></div><h3 class="mt-5 font-semibold">创建未来等级 Override</h3><div class="mt-3 grid gap-2"><select v-model="overrideTier" aria-label="Override 等级" class="rounded-xl border px-3 py-2 dark:bg-dark-900"><option value="standard">Standard</option><option value="priority">Priority</option><option value="strategic">Strategic</option></select><input v-model="overrideReason" aria-label="Override 原因" class="rounded-xl border px-3 py-2 dark:bg-dark-900" placeholder="必填原因" /><input v-model.number="overrideDays" aria-label="Override 天数" type="number" min="1" max="180" class="rounded-xl border px-3 py-2 dark:bg-dark-900" /><button :disabled="acting" class="rounded-xl bg-primary-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" @click="createOverride">创建审计 Override</button></div></article>
      </section>
    </div>
  </AppLayout>
</template>

<script setup lang="ts">
import { defineComponent, h, onBeforeUnmount, onMounted, ref } from 'vue'
import AppLayout from '@/components/layout/AppLayout.vue'
import { createCustomerTierOverride, getCustomerTiers, getCustomerTierUser, updateCustomerTierSettings, type CustomerTier, type CustomerTierExplanation, type CustomerTierSnapshot } from '@/api/admin/customerTiers'
const Metric = defineComponent({ props: { label: String, value: String }, setup: (props) => () => h('div', { class: 'rounded-xl bg-gray-50 p-3 dark:bg-dark-900' }, [h('span', { class: 'block text-xs text-gray-500' }, props.label), h('strong', props.value)]) })
const snapshot = ref<CustomerTierSnapshot | null>(null); const explanation = ref<CustomerTierExplanation | null>(null); const enabled = ref(false); const loading = ref(false); const acting = ref(false); const error = ref(''); const search = ref(''); const overrideTier = ref<CustomerTier>('priority'); const overrideReason = ref(''); const overrideDays = ref(30); let listController: AbortController | null = null; let detailController: AbortController | null = null; let listRequest = 0; let detailRequest = 0; let stopped = false
async function load(page = snapshot.value?.page || 1) { if (stopped) return; listController?.abort(); const current = new AbortController(); listController = current; const request = ++listRequest; loading.value = true; error.value = ''; try { const next = await getCustomerTiers(current.signal, { page, page_size: 50, search: search.value }); if (stopped || current.signal.aborted || request !== listRequest) return; snapshot.value = next; enabled.value = next.enabled } catch (cause) { if (!stopped && !current.signal.aborted && request === listRequest) error.value = cause instanceof Error ? cause.message : '加载失败' } finally { if (!stopped && request === listRequest) loading.value = false } }
async function selectUser(userId: number) { if (stopped) return; detailController?.abort(); const current = new AbortController(); detailController = current; const request = ++detailRequest; try { const next = await getCustomerTierUser(userId, current.signal); if (!stopped && !current.signal.aborted && request === detailRequest) explanation.value = next } catch (cause) { if (!stopped && !current.signal.aborted && request === detailRequest) error.value = cause instanceof Error ? cause.message : '解释加载失败' } }
async function act(action: () => Promise<unknown>) { if (acting.value || stopped) return; acting.value = true; try { await action(); if (stopped) return; await load(); if (stopped) return; if (explanation.value) await selectUser(explanation.value.current.user_id) } catch (cause) { if (!stopped) error.value = cause instanceof Error ? cause.message : '操作失败' } finally { if (!stopped) acting.value = false } }
function saveSettings() { void act(() => updateCustomerTierSettings(enabled.value)) }
function createOverride() { if (!explanation.value) return; void act(() => createCustomerTierOverride(explanation.value!.current.user_id, overrideTier.value, overrideReason.value, overrideDays.value)) }
function tierLabel(tier: CustomerTier) { return ({ standard: 'Standard', priority: 'Priority', strategic: 'Strategic' } as const)[tier] }
function formatCNY(fen: number) { return `¥${(fen / 100).toFixed(2)}` }
function formatCredits(micros: number) { return `${(micros / 1_000_000).toFixed(2)} 额度` }
function sourceConclusion(included: boolean, reason?: string) { if (included) return '计入'; return ({ unresolved_paid_value: '未找到精确付款关联', ambiguous_paid_value: '同一订单存在多条付款记录，等待核对', non_sale_purpose: '礼品、补偿或内部额度，不计入', status_not_completed: '订单尚未完成', native_checkout_duplicate: '已由站内订单计入', not_sold: '未标记为已售', not_attributed_to_user: '未归因到该用户', fully_refunded: '已全额退款' } as Record<string,string>)[reason || ''] || '未计入' }
function formatTime(value: string) { return new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(Date.parse(value)) }
onMounted(() => { stopped = false; void load() }); onBeforeUnmount(() => { stopped = true; listController?.abort(); detailController?.abort() })
</script>
