// Code generated by ent, DO NOT EDIT.

package adminmenu

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldName, v))
}

// NameEn applies equality check predicate on the "name_en" field. It's identical to NameEnEQ.
func NameEn(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldNameEn, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldType, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldPath, v))
}

// Component applies equality check predicate on the "component" field. It's identical to ComponentEQ.
func Component(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldComponent, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldIcon, v))
}

// PermissionKey applies equality check predicate on the "permission_key" field. It's identical to PermissionKeyEQ.
func PermissionKey(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldPermissionKey, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldSortOrder, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldName, v))
}

// NameEnEQ applies the EQ predicate on the "name_en" field.
func NameEnEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldNameEn, v))
}

// NameEnNEQ applies the NEQ predicate on the "name_en" field.
func NameEnNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldNameEn, v))
}

// NameEnIn applies the In predicate on the "name_en" field.
func NameEnIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldNameEn, vs...))
}

// NameEnNotIn applies the NotIn predicate on the "name_en" field.
func NameEnNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldNameEn, vs...))
}

// NameEnGT applies the GT predicate on the "name_en" field.
func NameEnGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldNameEn, v))
}

// NameEnGTE applies the GTE predicate on the "name_en" field.
func NameEnGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldNameEn, v))
}

// NameEnLT applies the LT predicate on the "name_en" field.
func NameEnLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldNameEn, v))
}

// NameEnLTE applies the LTE predicate on the "name_en" field.
func NameEnLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldNameEn, v))
}

// NameEnContains applies the Contains predicate on the "name_en" field.
func NameEnContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldNameEn, v))
}

// NameEnHasPrefix applies the HasPrefix predicate on the "name_en" field.
func NameEnHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldNameEn, v))
}

// NameEnHasSuffix applies the HasSuffix predicate on the "name_en" field.
func NameEnHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldNameEn, v))
}

// NameEnEqualFold applies the EqualFold predicate on the "name_en" field.
func NameEnEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldNameEn, v))
}

// NameEnContainsFold applies the ContainsFold predicate on the "name_en" field.
func NameEnContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldNameEn, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldType, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldPath, v))
}

// ComponentEQ applies the EQ predicate on the "component" field.
func ComponentEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldComponent, v))
}

// ComponentNEQ applies the NEQ predicate on the "component" field.
func ComponentNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldComponent, v))
}

// ComponentIn applies the In predicate on the "component" field.
func ComponentIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldComponent, vs...))
}

// ComponentNotIn applies the NotIn predicate on the "component" field.
func ComponentNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldComponent, vs...))
}

// ComponentGT applies the GT predicate on the "component" field.
func ComponentGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldComponent, v))
}

// ComponentGTE applies the GTE predicate on the "component" field.
func ComponentGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldComponent, v))
}

// ComponentLT applies the LT predicate on the "component" field.
func ComponentLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldComponent, v))
}

// ComponentLTE applies the LTE predicate on the "component" field.
func ComponentLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldComponent, v))
}

// ComponentContains applies the Contains predicate on the "component" field.
func ComponentContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldComponent, v))
}

// ComponentHasPrefix applies the HasPrefix predicate on the "component" field.
func ComponentHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldComponent, v))
}

// ComponentHasSuffix applies the HasSuffix predicate on the "component" field.
func ComponentHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldComponent, v))
}

// ComponentEqualFold applies the EqualFold predicate on the "component" field.
func ComponentEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldComponent, v))
}

// ComponentContainsFold applies the ContainsFold predicate on the "component" field.
func ComponentContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldComponent, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldIcon, v))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldIcon, v))
}

// PermissionKeyEQ applies the EQ predicate on the "permission_key" field.
func PermissionKeyEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldPermissionKey, v))
}

// PermissionKeyNEQ applies the NEQ predicate on the "permission_key" field.
func PermissionKeyNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldPermissionKey, v))
}

// PermissionKeyIn applies the In predicate on the "permission_key" field.
func PermissionKeyIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldPermissionKey, vs...))
}

// PermissionKeyNotIn applies the NotIn predicate on the "permission_key" field.
func PermissionKeyNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldPermissionKey, vs...))
}

// PermissionKeyGT applies the GT predicate on the "permission_key" field.
func PermissionKeyGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldPermissionKey, v))
}

// PermissionKeyGTE applies the GTE predicate on the "permission_key" field.
func PermissionKeyGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldPermissionKey, v))
}

// PermissionKeyLT applies the LT predicate on the "permission_key" field.
func PermissionKeyLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldPermissionKey, v))
}

// PermissionKeyLTE applies the LTE predicate on the "permission_key" field.
func PermissionKeyLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldPermissionKey, v))
}

// PermissionKeyContains applies the Contains predicate on the "permission_key" field.
func PermissionKeyContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldPermissionKey, v))
}

// PermissionKeyHasPrefix applies the HasPrefix predicate on the "permission_key" field.
func PermissionKeyHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldPermissionKey, v))
}

// PermissionKeyHasSuffix applies the HasSuffix predicate on the "permission_key" field.
func PermissionKeyHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldPermissionKey, v))
}

// PermissionKeyEqualFold applies the EqualFold predicate on the "permission_key" field.
func PermissionKeyEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldPermissionKey, v))
}

// PermissionKeyContainsFold applies the ContainsFold predicate on the "permission_key" field.
func PermissionKeyContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldPermissionKey, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldSortOrder, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AdminMenu {
	return predicate.AdminMenu(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminMenu) predicate.AdminMenu {
	return predicate.AdminMenu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminMenu) predicate.AdminMenu {
	return predicate.AdminMenu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminMenu) predicate.AdminMenu {
	return predicate.AdminMenu(sql.NotPredicates(p))
}
