package server

// scannerDescMap 将 "METHOD /admin/<bizPath>" 映射为中文 API 简介, 供路由扫描器
// 在首次同步或历史占位值 ("METHOD path") 覆盖时写入 admin_apis.description.
//
// 维护规则:
//  1. 键必须与 ScanAdminAPIs 输出一致: METHOD 大写 + 单空格 + 以 "/admin/" 开头的业务路径.
//  2. 新增/修改路由时, 请同步补充或调整本表; 未命中的路由将回退为 "METHOD path" 占位.
//  3. 描述尽量采用 "动词 + 业务对象" 结构, 控制在 15-20 字内, 避免与 path 列冗余.
//  4. 管理员在 API 管理页手工修改后的值受 UpsertAPIs 保护 (仅当新值与旧值不同才覆盖).
var scannerDescMap = map[string]string{
	// ==================== 仪表盘 (dashboard) ====================
	"GET /admin/dashboard/snapshot-v2":           "仪表盘快照 (v2)",
	"GET /admin/dashboard/stats":                 "仪表盘统计概览",
	"GET /admin/dashboard/realtime":              "实时指标数据",
	"GET /admin/dashboard/trend":                 "使用趋势",
	"GET /admin/dashboard/models":                "模型使用统计",
	"GET /admin/dashboard/groups":                "分组使用统计",
	"GET /admin/dashboard/api-keys-trend":        "API Key 使用趋势",
	"GET /admin/dashboard/users-trend":           "用户使用趋势",
	"GET /admin/dashboard/users-ranking":         "用户消费排行",
	"POST /admin/dashboard/users-usage":          "批量查询用户用量",
	"POST /admin/dashboard/api-keys-usage":       "批量查询 API Key 用量",
	"GET /admin/dashboard/user-breakdown":        "用户分布明细",
	"POST /admin/dashboard/aggregation/backfill": "回填聚合数据",

	// ==================== 用户管理 (users) ====================
	"GET /admin/users":                     "分页查询用户列表",
	"GET /admin/users/:id":                 "获取用户详情",
	"POST /admin/users":                    "新建用户",
	"PUT /admin/users/:id":                 "编辑用户信息",
	"DELETE /admin/users/:id":              "删除用户",
	"POST /admin/users/:id/balance":        "调整用户余额",
	"GET /admin/users/:id/api-keys":        "用户 API Key 列表",
	"GET /admin/users/:id/usage":           "用户使用明细",
	"GET /admin/users/:id/balance-history": "用户余额变动历史",
	"POST /admin/users/:id/replace-group":  "替换用户所属分组",
	"GET /admin/users/:id/attributes":      "查询用户属性值",
	"PUT /admin/users/:id/attributes":      "修改用户属性值",
	"GET /admin/users/:id/subscriptions":   "用户订阅列表",

	// ==================== 代理商管理 (agents) ====================
	"GET /admin/agents":                               "分页查询代理商列表",
	"GET /admin/agents/rates":                         "查询代理商费率配置",
	"PUT /admin/agents/rates":                         "修改代理商费率配置",
	"GET /admin/agents/level-rules":                   "查询代理商等级规则",
	"PUT /admin/agents/level-rules":                   "修改代理商等级规则",
	"GET /admin/agents/settlement-settings":           "查询代理结算门槛",
	"PUT /admin/agents/settlement-settings":           "修改代理结算门槛",
	"GET /admin/agents/settlement-candidates":         "查询代理结算列表",
	"POST /admin/agents/level-evaluations/run":        "手动执行全部代理商等级评估",
	"GET /admin/agents/:id":                           "代理商详情",
	"GET /admin/agents/:id/users":                     "代理商绑定用户列表",
	"POST /admin/agents/:id/users/bind":               "绑定代理商用户",
	"GET /admin/agents/:id/commissions":               "代理商佣金记录",
	"GET /admin/agents/:id/settlements":               "代理商结算记录",
	"POST /admin/agents/:id/settlements":              "创建代理商结算",
	"GET /admin/agents/:id/payment-profile":           "查看代理收款资料",
	"GET /admin/agents/:id/payment-profile/alipay-qr": "查看代理收款码",
	"GET /admin/agents/:id/rate":                      "查询代理商单独费率",
	"PUT /admin/agents/:id/rate":                      "修改代理商单独费率",
	"POST /admin/agents/:id/level-evaluations/run":    "手动执行单个代理商等级评估",

	// ==================== 分组管理 (groups) ====================
	"GET /admin/groups":                         "分页查询分组列表",
	"GET /admin/groups/all":                     "获取全部分组",
	"GET /admin/groups/usage-summary":           "分组用量汇总",
	"GET /admin/groups/capacity-summary":        "分组容量汇总",
	"PUT /admin/groups/sort-order":              "调整分组排序",
	"GET /admin/groups/:id":                     "分组详情",
	"POST /admin/groups":                        "新建分组",
	"PUT /admin/groups/:id":                     "编辑分组",
	"DELETE /admin/groups/:id":                  "删除分组",
	"GET /admin/groups/:id/stats":               "分组统计数据",
	"GET /admin/groups/:id/rate-multipliers":    "分组倍率配置",
	"PUT /admin/groups/:id/rate-multipliers":    "批量设置分组倍率",
	"DELETE /admin/groups/:id/rate-multipliers": "清除分组倍率配置",
	"GET /admin/groups/:id/api-keys":            "分组下 API Key 列表",
	"GET /admin/groups/:id/subscriptions":       "分组订阅列表",

	// ==================== 账号管理 (accounts) ====================
	"GET /admin/accounts":                                   "分页查询账号列表",
	"GET /admin/accounts/:id":                               "账号详情",
	"POST /admin/accounts":                                  "新建账号",
	"POST /admin/accounts/check-mixed-channel":              "检查混合渠道账号",
	"POST /admin/accounts/sync/crs":                         "同步 CRS 账号",
	"POST /admin/accounts/sync/crs/preview":                 "预览 CRS 同步",
	"PUT /admin/accounts/:id":                               "编辑账号",
	"DELETE /admin/accounts/:id":                            "删除账号",
	"POST /admin/accounts/:id/test":                         "测试账号连通性",
	"POST /admin/accounts/:id/recover-state":                "恢复账号状态",
	"POST /admin/accounts/:id/refresh":                      "刷新账号信息",
	"POST /admin/accounts/:id/set-privacy":                  "设置账号隐私模式",
	"POST /admin/accounts/:id/refresh-tier":                 "刷新账号等级",
	"GET /admin/accounts/:id/stats":                         "账号统计数据",
	"POST /admin/accounts/:id/clear-error":                  "清除账号错误标记",
	"GET /admin/accounts/:id/usage":                         "账号使用明细",
	"GET /admin/accounts/:id/today-stats":                   "账号今日统计",
	"POST /admin/accounts/today-stats/batch":                "批量查询今日统计",
	"POST /admin/accounts/:id/clear-rate-limit":             "解除账号限流",
	"POST /admin/accounts/:id/reset-quota":                  "重置账号配额",
	"GET /admin/accounts/:id/temp-unschedulable":            "查询临时不可调度记录",
	"DELETE /admin/accounts/:id/temp-unschedulable":         "清除临时不可调度记录",
	"POST /admin/accounts/:id/schedulable":                  "设置账号可调度状态",
	"GET /admin/accounts/:id/models":                        "账号可用模型列表",
	"POST /admin/accounts/batch":                            "批量新建账号",
	"GET /admin/accounts/data":                              "导出账号数据",
	"POST /admin/accounts/data":                             "导入账号数据",
	"POST /admin/accounts/batch-update-credentials":         "批量更新账号凭证",
	"POST /admin/accounts/batch-refresh-tier":               "批量刷新账号等级",
	"POST /admin/accounts/bulk-update":                      "批量修改账号属性",
	"POST /admin/accounts/batch-clear-error":                "批量清除账号错误",
	"POST /admin/accounts/batch-refresh":                    "批量刷新账号",
	"GET /admin/accounts/antigravity/default-model-mapping": "Antigravity 默认模型映射",
	"POST /admin/accounts/generate-auth-url":                "生成 Claude 授权链接",
	"POST /admin/accounts/generate-setup-token-url":         "生成 Claude Setup Token 链接",
	"POST /admin/accounts/exchange-code":                    "交换 Claude 授权码",
	"POST /admin/accounts/exchange-setup-token-code":        "交换 Claude Setup Token",
	"POST /admin/accounts/cookie-auth":                      "Claude Cookie 登录",
	"POST /admin/accounts/setup-token-cookie-auth":          "Setup Token Cookie 登录",
	"GET /admin/accounts/:id/scheduled-test-plans":          "账号定时测试计划",

	// ==================== 公告管理 (announcements) ====================
	"GET /admin/announcements":                 "分页查询公告列表",
	"POST /admin/announcements":                "发布公告",
	"GET /admin/announcements/:id":             "公告详情",
	"PUT /admin/announcements/:id":             "编辑公告",
	"DELETE /admin/announcements/:id":          "删除公告",
	"GET /admin/announcements/:id/read-status": "公告已读状态",

	// ==================== 反馈管理 (feedbacks) ====================
	"GET /admin/feedbacks":               "分页查询反馈列表",
	"GET /admin/feedbacks/:id":           "反馈详情",
	"POST /admin/feedbacks/:id/replies":  "回复反馈",
	"PUT /admin/feedbacks/:id/status":    "修改反馈状态",
	"PUT /admin/feedbacks/:id/priority":  "调整反馈优先级",
	"PUT /admin/feedbacks/batch-status":  "批量修改反馈状态",
	"DELETE /admin/feedbacks/:id":        "删除反馈",
	"POST /admin/feedbacks/batch-delete": "批量删除反馈",

	// ==================== OpenAI OAuth (openai) ====================
	"POST /admin/openai/generate-auth-url":    "生成 OpenAI 授权链接",
	"POST /admin/openai/exchange-code":        "交换 OpenAI 授权码",
	"POST /admin/openai/refresh-token":        "刷新 OpenAI 令牌",
	"POST /admin/openai/accounts/:id/refresh": "刷新指定账号 OpenAI 令牌",
	"POST /admin/openai/create-from-oauth":    "从 OAuth 结果创建账号",

	// ==================== Gemini OAuth (gemini) ====================
	"POST /admin/gemini/oauth/auth-url":      "生成 Gemini 授权链接",
	"POST /admin/gemini/oauth/exchange-code": "交换 Gemini 授权码",
	"GET /admin/gemini/oauth/capabilities":   "Gemini OAuth 能力",

	// ==================== Antigravity OAuth (antigravity) ====================
	"POST /admin/antigravity/oauth/auth-url":      "生成 Antigravity 授权链接",
	"POST /admin/antigravity/oauth/exchange-code": "交换 Antigravity 授权码",
	"POST /admin/antigravity/oauth/refresh-token": "刷新 Antigravity 令牌",

	// ==================== 代理管理 (proxies) ====================
	"GET /admin/proxies":                    "分页查询代理列表",
	"GET /admin/proxies/all":                "获取全部代理",
	"GET /admin/proxies/data":               "导出代理数据",
	"POST /admin/proxies/data":              "导入代理数据",
	"GET /admin/proxies/:id":                "代理详情",
	"POST /admin/proxies":                   "新建代理",
	"PUT /admin/proxies/:id":                "编辑代理",
	"DELETE /admin/proxies/:id":             "删除代理",
	"POST /admin/proxies/:id/test":          "测试代理连通性",
	"POST /admin/proxies/:id/quality-check": "代理质量检测",
	"GET /admin/proxies/:id/stats":          "代理统计数据",
	"GET /admin/proxies/:id/accounts":       "代理下账号列表",
	"POST /admin/proxies/batch-delete":      "批量删除代理",
	"POST /admin/proxies/batch":             "批量新建代理",

	// ==================== 卡密管理 (redeem-codes) ====================
	"GET /admin/redeem-codes":                    "分页查询卡密列表",
	"GET /admin/redeem-codes/stats":              "卡密统计数据",
	"GET /admin/redeem-codes/export":             "导出卡密",
	"GET /admin/redeem-codes/billing":            "卡密账单列表",
	"GET /admin/redeem-codes/:id":                "卡密详情",
	"POST /admin/redeem-codes/create-and-redeem": "创建并立即兑换卡密",
	"POST /admin/redeem-codes/generate":          "批量生成卡密",
	"DELETE /admin/redeem-codes/:id":             "删除卡密",
	"POST /admin/redeem-codes/batch-delete":      "批量删除卡密",
	"POST /admin/redeem-codes/:id/expire":        "作废卡密",

	// ==================== 优惠码管理 (promo-codes) ====================
	"GET /admin/promo-codes":            "分页查询优惠码列表",
	"GET /admin/promo-codes/:id":        "优惠码详情",
	"POST /admin/promo-codes":           "新建优惠码",
	"PUT /admin/promo-codes/:id":        "编辑优惠码",
	"DELETE /admin/promo-codes/:id":     "删除优惠码",
	"GET /admin/promo-codes/:id/usages": "优惠码使用记录",

	// ==================== 系统设置 (settings) ====================
	"GET /admin/settings":                                   "获取系统设置",
	"PUT /admin/settings":                                   "修改系统设置",
	"POST /admin/settings/test-smtp":                        "测试 SMTP 连通性",
	"POST /admin/settings/send-test-email":                  "发送测试邮件",
	"GET /admin/settings/admin-api-key":                     "获取 Admin API Key",
	"POST /admin/settings/admin-api-key/regenerate":         "重新生成 Admin API Key",
	"DELETE /admin/settings/admin-api-key":                  "删除 Admin API Key",
	"GET /admin/settings/overload-cooldown":                 "529 过载冷却配置",
	"PUT /admin/settings/overload-cooldown":                 "修改 529 过载冷却配置",
	"GET /admin/settings/stream-timeout":                    "流超时处理配置",
	"PUT /admin/settings/stream-timeout":                    "修改流超时处理配置",
	"GET /admin/settings/rectifier":                         "请求整流器配置",
	"PUT /admin/settings/rectifier":                         "修改请求整流器配置",
	"GET /admin/settings/beta-policy":                       "Beta 策略配置",
	"PUT /admin/settings/beta-policy":                       "修改 Beta 策略配置",
	"GET /admin/settings/openai-fast-policy":                "OpenAI fast/flex 策略配置",
	"PUT /admin/settings/openai-fast-policy":                "修改 OpenAI fast/flex 策略配置",
	"GET /admin/settings/web-search-emulation":              "Web Search 模拟配置",
	"PUT /admin/settings/web-search-emulation":              "修改 Web Search 模拟配置",
	"POST /admin/settings/web-search-emulation/test":        "测试 Web Search 模拟",
	"POST /admin/settings/web-search-emulation/reset-usage": "重置 Web Search 用量",

	// ==================== 数据管理 (data-management) ====================
	"GET /admin/data-management/agent/health":                                        "数据管理代理健康检查",
	"GET /admin/data-management/config":                                              "数据管理配置",
	"PUT /admin/data-management/config":                                              "修改数据管理配置",
	"GET /admin/data-management/sources/:source_type/profiles":                       "数据源配置列表",
	"POST /admin/data-management/sources/:source_type/profiles":                      "新建数据源配置",
	"PUT /admin/data-management/sources/:source_type/profiles/:profile_id":           "编辑数据源配置",
	"DELETE /admin/data-management/sources/:source_type/profiles/:profile_id":        "删除数据源配置",
	"POST /admin/data-management/sources/:source_type/profiles/:profile_id/activate": "激活数据源配置",
	"POST /admin/data-management/s3/test":                                            "测试 S3 连通性",
	"GET /admin/data-management/s3/profiles":                                         "S3 配置列表",
	"POST /admin/data-management/s3/profiles":                                        "新建 S3 配置",
	"PUT /admin/data-management/s3/profiles/:profile_id":                             "编辑 S3 配置",
	"DELETE /admin/data-management/s3/profiles/:profile_id":                          "删除 S3 配置",
	"POST /admin/data-management/s3/profiles/:profile_id/activate":                   "激活 S3 配置",
	"POST /admin/data-management/backups":                                            "创建备份任务",
	"GET /admin/data-management/backups":                                             "查询备份任务列表",
	"GET /admin/data-management/backups/:job_id":                                     "备份任务详情",

	// ==================== 数据备份 (backups) ====================
	"GET /admin/backups/s3-config":        "S3 备份配置",
	"PUT /admin/backups/s3-config":        "修改 S3 备份配置",
	"POST /admin/backups/s3-config/test":  "测试 S3 备份连通性",
	"GET /admin/backups/schedule":         "备份计划配置",
	"PUT /admin/backups/schedule":         "修改备份计划",
	"POST /admin/backups":                 "创建备份",
	"GET /admin/backups":                  "查询备份列表",
	"GET /admin/backups/:id":              "备份详情",
	"DELETE /admin/backups/:id":           "删除备份",
	"GET /admin/backups/:id/download-url": "备份下载链接",
	"POST /admin/backups/:id/restore":     "从备份恢复",

	// ==================== 运维监控 (ops) ====================
	"GET /admin/ops/concurrency":                                    "并发统计",
	"GET /admin/ops/user-concurrency":                               "用户并发统计",
	"GET /admin/ops/account-availability":                           "账号可用性监控",
	"GET /admin/ops/realtime-traffic":                               "实时流量汇总",
	"GET /admin/ops/alert-rules":                                    "告警规则列表",
	"POST /admin/ops/alert-rules":                                   "创建告警规则",
	"PUT /admin/ops/alert-rules/:id":                                "编辑告警规则",
	"DELETE /admin/ops/alert-rules/:id":                             "删除告警规则",
	"GET /admin/ops/alert-events":                                   "告警事件列表",
	"GET /admin/ops/alert-events/:id":                               "告警事件详情",
	"PUT /admin/ops/alert-events/:id/status":                        "修改告警事件状态",
	"POST /admin/ops/alert-silences":                                "创建告警静默规则",
	"GET /admin/ops/email-notification/config":                      "邮件通知配置",
	"PUT /admin/ops/email-notification/config":                      "修改邮件通知配置",
	"GET /admin/ops/webhook-notification/config":                    "群通知配置",
	"PUT /admin/ops/webhook-notification/config":                    "修改群通知配置",
	"POST /admin/ops/webhook-notification/test":                     "发送群通知测试",
	"GET /admin/ops/runtime/alert":                                  "告警运行时设置",
	"PUT /admin/ops/runtime/alert":                                  "修改告警运行时设置",
	"GET /admin/ops/runtime/logging":                                "日志运行时配置",
	"PUT /admin/ops/runtime/logging":                                "修改日志运行时配置",
	"POST /admin/ops/runtime/logging/reset":                         "重置日志运行时配置",
	"GET /admin/ops/advanced-settings":                              "高级设置",
	"PUT /admin/ops/advanced-settings":                              "修改高级设置",
	"GET /admin/ops/settings/metric-thresholds":                     "指标阈值配置",
	"PUT /admin/ops/settings/metric-thresholds":                     "修改指标阈值",
	"GET /admin/ops/ws/qps":                                         "实时 QPS WebSocket",
	"GET /admin/ops/errors":                                         "错误日志列表",
	"GET /admin/ops/errors/:id":                                     "错误日志详情",
	"GET /admin/ops/errors/:id/retries":                             "错误重试记录",
	"POST /admin/ops/errors/:id/retry":                              "重试错误请求",
	"PUT /admin/ops/errors/:id/resolve":                             "标记错误已解决",
	"GET /admin/ops/request-errors":                                 "请求错误列表",
	"GET /admin/ops/request-errors/:id":                             "请求错误详情",
	"GET /admin/ops/request-errors/:id/upstream-errors":             "请求上游错误列表",
	"POST /admin/ops/request-errors/:id/retry-client":               "向客户端重试请求",
	"POST /admin/ops/request-errors/:id/upstream-errors/:idx/retry": "重试指定上游错误",
	"PUT /admin/ops/request-errors/:id/resolve":                     "解决请求错误",
	"GET /admin/ops/upstream-errors":                                "上游错误列表",
	"GET /admin/ops/upstream-errors/:id":                            "上游错误详情",
	"POST /admin/ops/upstream-errors/:id/retry":                     "重试上游错误",
	"PUT /admin/ops/upstream-errors/:id/resolve":                    "解决上游错误",
	"GET /admin/ops/requests":                                       "请求明细列表",
	"GET /admin/ops/system-logs":                                    "系统日志列表",
	"POST /admin/ops/system-logs/cleanup":                           "清理系统日志",
	"GET /admin/ops/system-logs/health":                             "日志系统健康状态",
	"GET /admin/ops/dashboard/snapshot-v2":                          "运维仪表盘快照 (v2)",
	"GET /admin/ops/dashboard/overview":                             "运维仪表盘概览",
	"GET /admin/ops/dashboard/throughput-trend":                     "吞吐量趋势",
	"GET /admin/ops/dashboard/latency-histogram":                    "延迟直方图",
	"GET /admin/ops/dashboard/error-trend":                          "错误趋势",
	"GET /admin/ops/dashboard/error-distribution":                   "错误分布",
	"GET /admin/ops/dashboard/openai-token-stats":                   "OpenAI Token 统计",

	// ==================== 系统管理 (system) ====================
	"GET /admin/system/version":       "系统版本信息",
	"GET /admin/system/check-updates": "检查系统更新",
	"POST /admin/system/update":       "执行系统更新",
	"POST /admin/system/rollback":     "回滚系统版本",
	"POST /admin/system/restart":      "重启服务",

	// ==================== 订阅管理 (subscriptions) ====================
	"GET /admin/subscriptions":                  "分页查询订阅列表",
	"GET /admin/subscriptions/:id":              "订阅详情",
	"GET /admin/subscriptions/:id/progress":     "订阅进度",
	"POST /admin/subscriptions/assign":          "分配订阅",
	"POST /admin/subscriptions/bulk-assign":     "批量分配订阅",
	"POST /admin/subscriptions/:id/extend":      "订阅延期",
	"POST /admin/subscriptions/:id/reset-quota": "重置订阅配额",
	"DELETE /admin/subscriptions/:id":           "撤销订阅",

	// ==================== 使用记录 (usage) ====================
	"GET /admin/usage":                           "分页查询使用记录",
	"GET /admin/usage/stats":                     "使用统计数据",
	"GET /admin/usage/search-users":              "搜索用户使用记录",
	"GET /admin/usage/search-api-keys":           "搜索 API Key 使用记录",
	"GET /admin/usage/cleanup-tasks":             "使用记录清理任务列表",
	"POST /admin/usage/cleanup-tasks":            "创建使用记录清理任务",
	"POST /admin/usage/cleanup-tasks/:id/cancel": "取消使用记录清理任务",

	// ==================== 用户属性 (user-attributes) ====================
	"GET /admin/user-attributes":         "用户属性定义列表",
	"POST /admin/user-attributes":        "创建用户属性定义",
	"POST /admin/user-attributes/batch":  "批量查询用户属性值",
	"PUT /admin/user-attributes/reorder": "调整属性定义排序",
	"PUT /admin/user-attributes/:id":     "编辑用户属性定义",
	"DELETE /admin/user-attributes/:id":  "删除用户属性定义",

	// ==================== 定时测试计划 (scheduled-test-plans) ====================
	"POST /admin/scheduled-test-plans":            "创建定时测试计划",
	"PUT /admin/scheduled-test-plans/:id":         "编辑定时测试计划",
	"DELETE /admin/scheduled-test-plans/:id":      "删除定时测试计划",
	"GET /admin/scheduled-test-plans/:id/results": "定时测试结果列表",

	// ==================== 错误透传规则 (error-passthrough-rules) ====================
	"GET /admin/error-passthrough-rules":        "分页查询错误透传规则",
	"GET /admin/error-passthrough-rules/:id":    "错误透传规则详情",
	"POST /admin/error-passthrough-rules":       "新建错误透传规则",
	"PUT /admin/error-passthrough-rules/:id":    "编辑错误透传规则",
	"DELETE /admin/error-passthrough-rules/:id": "删除错误透传规则",

	// ==================== TLS 指纹 (tls-fingerprint-profiles) ====================
	"GET /admin/tls-fingerprint-profiles":        "分页查询 TLS 指纹配置",
	"GET /admin/tls-fingerprint-profiles/:id":    "TLS 指纹配置详情",
	"POST /admin/tls-fingerprint-profiles":       "新建 TLS 指纹配置",
	"PUT /admin/tls-fingerprint-profiles/:id":    "编辑 TLS 指纹配置",
	"DELETE /admin/tls-fingerprint-profiles/:id": "删除 TLS 指纹配置",

	// ==================== 渠道管理 (channels) ====================
	"GET /admin/channels":               "分页查询渠道列表",
	"GET /admin/channels/model-pricing": "渠道模型默认定价",
	"GET /admin/channels/:id":           "渠道详情",
	"POST /admin/channels":              "新建渠道",
	"PUT /admin/channels/:id":           "编辑渠道",
	"DELETE /admin/channels/:id":        "删除渠道",

	// ==================== 供应商考察 (suppliers) ====================
	"GET /admin/suppliers":            "分页查询供应商列表",
	"GET /admin/suppliers/:id":        "供应商详情",
	"POST /admin/suppliers":           "新建供应商",
	"PUT /admin/suppliers/:id":        "编辑供应商",
	"POST /admin/suppliers/:id/probe": "立即执行供应商探针",
	"DELETE /admin/suppliers/:id":     "删除供应商",

	// ==================== API Key 管理 (api-keys) ====================
	"PUT /admin/api-keys/:id": "更新 API Key 分组",

	// ==================== 充值订单 & 开票 (topup/invoice) ====================
	"GET /admin/topup/orders":                   "分页查询充值订单",
	"GET /admin/invoice/requests":               "分页查询开票请求",
	"POST /admin/invoice/requests/export":       "导出开票请求",
	"POST /admin/invoice/requests/:id/complete": "完成开票请求",
	"POST /admin/invoice/requests/:id/reject":   "拒绝开票请求",

	// ==================== RBAC 权限管理 (rbac) ====================
	"GET /admin/rbac/menu":                  "当前用户菜单",
	"GET /admin/rbac/me/permissions":        "当前用户权限列表",
	"GET /admin/rbac/user-menus/visibility": "用户菜单可见性",
	"PUT /admin/rbac/user-menus/visibility": "修改用户菜单可见性",
	"GET /admin/rbac/menus":                 "分页查询菜单列表",
	"GET /admin/rbac/menus/tree":            "菜单树结构",
	"POST /admin/rbac/menus":                "新建菜单",
	"PUT /admin/rbac/menus/:id":             "编辑菜单",
	"DELETE /admin/rbac/menus/:id":          "删除菜单",
	"GET /admin/rbac/apis":                  "分页查询 API 列表",
	"GET /admin/rbac/apis/all":              "获取全部 API",
	"GET /admin/rbac/apis/groups":           "API 分组列表",
	"POST /admin/rbac/apis":                 "新建 API 资源",
	"PUT /admin/rbac/apis/:id":              "编辑 API 资源",
	"DELETE /admin/rbac/apis/:id":           "删除 API 资源",
	"DELETE /admin/rbac/apis":               "批量删除 API 资源",
	"POST /admin/rbac/apis/sync":            "同步路由扫描 API",
	"GET /admin/rbac/roles":                 "分页查询角色列表",
	"POST /admin/rbac/roles":                "创建角色",
	"PUT /admin/rbac/roles/:id":             "编辑角色",
	"DELETE /admin/rbac/roles/:id":          "删除角色",
	"GET /admin/rbac/roles/:id/menus":       "角色已授权菜单",
	"PUT /admin/rbac/roles/:id/menus":       "修改角色授权菜单",
	"GET /admin/rbac/roles/:id/apis":        "角色已授权 API",
	"PUT /admin/rbac/roles/:id/apis":        "修改角色授权 API",
	"GET /admin/rbac/users/:id/roles":       "用户已分配角色",
	"PUT /admin/rbac/users/:id/roles":       "修改用户角色",
}

// lookupScannerDesc 返回给定 method+path 的中文简介; 未命中返回空串.
// ScanAdminAPIs 会在空串时回退为 "METHOD path" 占位.
func lookupScannerDesc(method, bizPath string) string {
	return scannerDescMap[method+" "+bizPath]
}
