// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/accountchangerecord"
	"github.com/bozhouDev/DragonCode-sub2api/ent/group"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
)

// AccountChangeRecordUpdate is the builder for updating AccountChangeRecord entities.
type AccountChangeRecordUpdate struct {
	config
	hooks    []Hook
	mutation *AccountChangeRecordMutation
}

// Where appends a list predicates to the AccountChangeRecordUpdate builder.
func (_u *AccountChangeRecordUpdate) Where(ps ...predicate.AccountChangeRecord) *AccountChangeRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AccountChangeRecordUpdate) SetUserID(v int64) *AccountChangeRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableUserID(v *int64) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *AccountChangeRecordUpdate) SetAssetType(v string) *AccountChangeRecordUpdate {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableAssetType(v *string) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *AccountChangeRecordUpdate) SetReason(v string) *AccountChangeRecordUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableReason(v *string) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetDelta sets the "delta" field.
func (_u *AccountChangeRecordUpdate) SetDelta(v float64) *AccountChangeRecordUpdate {
	_u.mutation.ResetDelta()
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableDelta(v *float64) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// AddDelta adds value to the "delta" field.
func (_u *AccountChangeRecordUpdate) AddDelta(v float64) *AccountChangeRecordUpdate {
	_u.mutation.AddDelta(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *AccountChangeRecordUpdate) SetSourceType(v string) *AccountChangeRecordUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableSourceType(v *string) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *AccountChangeRecordUpdate) SetSourceID(v int64) *AccountChangeRecordUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableSourceID(v *int64) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *AccountChangeRecordUpdate) AddSourceID(v int64) *AccountChangeRecordUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *AccountChangeRecordUpdate) ClearSourceID() *AccountChangeRecordUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetReferenceNo sets the "reference_no" field.
func (_u *AccountChangeRecordUpdate) SetReferenceNo(v string) *AccountChangeRecordUpdate {
	_u.mutation.SetReferenceNo(v)
	return _u
}

// SetNillableReferenceNo sets the "reference_no" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableReferenceNo(v *string) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetReferenceNo(*v)
	}
	return _u
}

// ClearReferenceNo clears the value of the "reference_no" field.
func (_u *AccountChangeRecordUpdate) ClearReferenceNo() *AccountChangeRecordUpdate {
	_u.mutation.ClearReferenceNo()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *AccountChangeRecordUpdate) SetOperatorUserID(v int64) *AccountChangeRecordUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableOperatorUserID(v *int64) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *AccountChangeRecordUpdate) AddOperatorUserID(v int64) *AccountChangeRecordUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *AccountChangeRecordUpdate) ClearOperatorUserID() *AccountChangeRecordUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AccountChangeRecordUpdate) SetNotes(v string) *AccountChangeRecordUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableNotes(v *string) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AccountChangeRecordUpdate) ClearNotes() *AccountChangeRecordUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AccountChangeRecordUpdate) SetGroupID(v int64) *AccountChangeRecordUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableGroupID(v *int64) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AccountChangeRecordUpdate) ClearGroupID() *AccountChangeRecordUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *AccountChangeRecordUpdate) SetValidityDays(v int) *AccountChangeRecordUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableValidityDays(v *int) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *AccountChangeRecordUpdate) AddValidityDays(v int) *AccountChangeRecordUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetDedupeKey sets the "dedupe_key" field.
func (_u *AccountChangeRecordUpdate) SetDedupeKey(v string) *AccountChangeRecordUpdate {
	_u.mutation.SetDedupeKey(v)
	return _u
}

// SetNillableDedupeKey sets the "dedupe_key" field if the given value is not nil.
func (_u *AccountChangeRecordUpdate) SetNillableDedupeKey(v *string) *AccountChangeRecordUpdate {
	if v != nil {
		_u.SetDedupeKey(*v)
	}
	return _u
}

// ClearDedupeKey clears the value of the "dedupe_key" field.
func (_u *AccountChangeRecordUpdate) ClearDedupeKey() *AccountChangeRecordUpdate {
	_u.mutation.ClearDedupeKey()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountChangeRecordUpdate) SetUser(v *User) *AccountChangeRecordUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AccountChangeRecordUpdate) SetGroup(v *Group) *AccountChangeRecordUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the AccountChangeRecordMutation object of the builder.
func (_u *AccountChangeRecordUpdate) Mutation() *AccountChangeRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountChangeRecordUpdate) ClearUser() *AccountChangeRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AccountChangeRecordUpdate) ClearGroup() *AccountChangeRecordUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountChangeRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountChangeRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountChangeRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountChangeRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountChangeRecordUpdate) check() error {
	if v, ok := _u.mutation.AssetType(); ok {
		if err := accountchangerecord.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.asset_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := accountchangerecord.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := accountchangerecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferenceNo(); ok {
		if err := accountchangerecord.ReferenceNoValidator(v); err != nil {
			return &ValidationError{Name: "reference_no", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.reference_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DedupeKey(); ok {
		if err := accountchangerecord.DedupeKeyValidator(v); err != nil {
			return &ValidationError{Name: "dedupe_key", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.dedupe_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountChangeRecord.user"`)
	}
	return nil
}

func (_u *AccountChangeRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountchangerecord.Table, accountchangerecord.Columns, sqlgraph.NewFieldSpec(accountchangerecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(accountchangerecord.FieldAssetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(accountchangerecord.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(accountchangerecord.FieldDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDelta(); ok {
		_spec.AddField(accountchangerecord.FieldDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(accountchangerecord.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(accountchangerecord.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(accountchangerecord.FieldSourceID, field.TypeInt64, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(accountchangerecord.FieldSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReferenceNo(); ok {
		_spec.SetField(accountchangerecord.FieldReferenceNo, field.TypeString, value)
	}
	if _u.mutation.ReferenceNoCleared() {
		_spec.ClearField(accountchangerecord.FieldReferenceNo, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(accountchangerecord.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(accountchangerecord.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(accountchangerecord.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(accountchangerecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(accountchangerecord.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(accountchangerecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(accountchangerecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DedupeKey(); ok {
		_spec.SetField(accountchangerecord.FieldDedupeKey, field.TypeString, value)
	}
	if _u.mutation.DedupeKeyCleared() {
		_spec.ClearField(accountchangerecord.FieldDedupeKey, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.UserTable,
			Columns: []string{accountchangerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.UserTable,
			Columns: []string{accountchangerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.GroupTable,
			Columns: []string{accountchangerecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.GroupTable,
			Columns: []string{accountchangerecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountchangerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountChangeRecordUpdateOne is the builder for updating a single AccountChangeRecord entity.
type AccountChangeRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountChangeRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *AccountChangeRecordUpdateOne) SetUserID(v int64) *AccountChangeRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableUserID(v *int64) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *AccountChangeRecordUpdateOne) SetAssetType(v string) *AccountChangeRecordUpdateOne {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableAssetType(v *string) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *AccountChangeRecordUpdateOne) SetReason(v string) *AccountChangeRecordUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableReason(v *string) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetDelta sets the "delta" field.
func (_u *AccountChangeRecordUpdateOne) SetDelta(v float64) *AccountChangeRecordUpdateOne {
	_u.mutation.ResetDelta()
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableDelta(v *float64) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// AddDelta adds value to the "delta" field.
func (_u *AccountChangeRecordUpdateOne) AddDelta(v float64) *AccountChangeRecordUpdateOne {
	_u.mutation.AddDelta(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *AccountChangeRecordUpdateOne) SetSourceType(v string) *AccountChangeRecordUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableSourceType(v *string) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *AccountChangeRecordUpdateOne) SetSourceID(v int64) *AccountChangeRecordUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableSourceID(v *int64) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *AccountChangeRecordUpdateOne) AddSourceID(v int64) *AccountChangeRecordUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *AccountChangeRecordUpdateOne) ClearSourceID() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetReferenceNo sets the "reference_no" field.
func (_u *AccountChangeRecordUpdateOne) SetReferenceNo(v string) *AccountChangeRecordUpdateOne {
	_u.mutation.SetReferenceNo(v)
	return _u
}

// SetNillableReferenceNo sets the "reference_no" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableReferenceNo(v *string) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetReferenceNo(*v)
	}
	return _u
}

// ClearReferenceNo clears the value of the "reference_no" field.
func (_u *AccountChangeRecordUpdateOne) ClearReferenceNo() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearReferenceNo()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *AccountChangeRecordUpdateOne) SetOperatorUserID(v int64) *AccountChangeRecordUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableOperatorUserID(v *int64) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *AccountChangeRecordUpdateOne) AddOperatorUserID(v int64) *AccountChangeRecordUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *AccountChangeRecordUpdateOne) ClearOperatorUserID() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AccountChangeRecordUpdateOne) SetNotes(v string) *AccountChangeRecordUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableNotes(v *string) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AccountChangeRecordUpdateOne) ClearNotes() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AccountChangeRecordUpdateOne) SetGroupID(v int64) *AccountChangeRecordUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableGroupID(v *int64) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AccountChangeRecordUpdateOne) ClearGroupID() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *AccountChangeRecordUpdateOne) SetValidityDays(v int) *AccountChangeRecordUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableValidityDays(v *int) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *AccountChangeRecordUpdateOne) AddValidityDays(v int) *AccountChangeRecordUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetDedupeKey sets the "dedupe_key" field.
func (_u *AccountChangeRecordUpdateOne) SetDedupeKey(v string) *AccountChangeRecordUpdateOne {
	_u.mutation.SetDedupeKey(v)
	return _u
}

// SetNillableDedupeKey sets the "dedupe_key" field if the given value is not nil.
func (_u *AccountChangeRecordUpdateOne) SetNillableDedupeKey(v *string) *AccountChangeRecordUpdateOne {
	if v != nil {
		_u.SetDedupeKey(*v)
	}
	return _u
}

// ClearDedupeKey clears the value of the "dedupe_key" field.
func (_u *AccountChangeRecordUpdateOne) ClearDedupeKey() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearDedupeKey()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountChangeRecordUpdateOne) SetUser(v *User) *AccountChangeRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AccountChangeRecordUpdateOne) SetGroup(v *Group) *AccountChangeRecordUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the AccountChangeRecordMutation object of the builder.
func (_u *AccountChangeRecordUpdateOne) Mutation() *AccountChangeRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountChangeRecordUpdateOne) ClearUser() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AccountChangeRecordUpdateOne) ClearGroup() *AccountChangeRecordUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the AccountChangeRecordUpdate builder.
func (_u *AccountChangeRecordUpdateOne) Where(ps ...predicate.AccountChangeRecord) *AccountChangeRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountChangeRecordUpdateOne) Select(field string, fields ...string) *AccountChangeRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountChangeRecord entity.
func (_u *AccountChangeRecordUpdateOne) Save(ctx context.Context) (*AccountChangeRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountChangeRecordUpdateOne) SaveX(ctx context.Context) *AccountChangeRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountChangeRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountChangeRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountChangeRecordUpdateOne) check() error {
	if v, ok := _u.mutation.AssetType(); ok {
		if err := accountchangerecord.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.asset_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := accountchangerecord.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := accountchangerecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferenceNo(); ok {
		if err := accountchangerecord.ReferenceNoValidator(v); err != nil {
			return &ValidationError{Name: "reference_no", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.reference_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DedupeKey(); ok {
		if err := accountchangerecord.DedupeKeyValidator(v); err != nil {
			return &ValidationError{Name: "dedupe_key", err: fmt.Errorf(`ent: validator failed for field "AccountChangeRecord.dedupe_key": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountChangeRecord.user"`)
	}
	return nil
}

func (_u *AccountChangeRecordUpdateOne) sqlSave(ctx context.Context) (_node *AccountChangeRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountchangerecord.Table, accountchangerecord.Columns, sqlgraph.NewFieldSpec(accountchangerecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountChangeRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountchangerecord.FieldID)
		for _, f := range fields {
			if !accountchangerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountchangerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(accountchangerecord.FieldAssetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(accountchangerecord.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(accountchangerecord.FieldDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDelta(); ok {
		_spec.AddField(accountchangerecord.FieldDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(accountchangerecord.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(accountchangerecord.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(accountchangerecord.FieldSourceID, field.TypeInt64, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(accountchangerecord.FieldSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReferenceNo(); ok {
		_spec.SetField(accountchangerecord.FieldReferenceNo, field.TypeString, value)
	}
	if _u.mutation.ReferenceNoCleared() {
		_spec.ClearField(accountchangerecord.FieldReferenceNo, field.TypeString)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(accountchangerecord.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(accountchangerecord.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(accountchangerecord.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(accountchangerecord.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(accountchangerecord.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(accountchangerecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(accountchangerecord.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DedupeKey(); ok {
		_spec.SetField(accountchangerecord.FieldDedupeKey, field.TypeString, value)
	}
	if _u.mutation.DedupeKeyCleared() {
		_spec.ClearField(accountchangerecord.FieldDedupeKey, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.UserTable,
			Columns: []string{accountchangerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.UserTable,
			Columns: []string{accountchangerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.GroupTable,
			Columns: []string{accountchangerecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountchangerecord.GroupTable,
			Columns: []string{accountchangerecord.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountChangeRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountchangerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
