// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/adminrolemenu"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// AdminRoleMenuUpdate is the builder for updating AdminRoleMenu entities.
type AdminRoleMenuUpdate struct {
	config
	hooks    []Hook
	mutation *AdminRoleMenuMutation
}

// Where appends a list predicates to the AdminRoleMenuUpdate builder.
func (_u *AdminRoleMenuUpdate) Where(ps ...predicate.AdminRoleMenu) *AdminRoleMenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *AdminRoleMenuUpdate) SetRoleID(v int64) *AdminRoleMenuUpdate {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *AdminRoleMenuUpdate) SetNillableRoleID(v *int64) *AdminRoleMenuUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *AdminRoleMenuUpdate) AddRoleID(v int64) *AdminRoleMenuUpdate {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *AdminRoleMenuUpdate) SetMenuID(v int64) *AdminRoleMenuUpdate {
	_u.mutation.ResetMenuID()
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *AdminRoleMenuUpdate) SetNillableMenuID(v *int64) *AdminRoleMenuUpdate {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// AddMenuID adds value to the "menu_id" field.
func (_u *AdminRoleMenuUpdate) AddMenuID(v int64) *AdminRoleMenuUpdate {
	_u.mutation.AddMenuID(v)
	return _u
}

// Mutation returns the AdminRoleMenuMutation object of the builder.
func (_u *AdminRoleMenuUpdate) Mutation() *AdminRoleMenuMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminRoleMenuUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRoleMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminRoleMenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRoleMenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AdminRoleMenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminrolemenu.Table, adminrolemenu.Columns, sqlgraph.NewFieldSpec(adminrolemenu.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(adminrolemenu.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(adminrolemenu.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MenuID(); ok {
		_spec.SetField(adminrolemenu.FieldMenuID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMenuID(); ok {
		_spec.AddField(adminrolemenu.FieldMenuID, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrolemenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminRoleMenuUpdateOne is the builder for updating a single AdminRoleMenu entity.
type AdminRoleMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminRoleMenuMutation
}

// SetRoleID sets the "role_id" field.
func (_u *AdminRoleMenuUpdateOne) SetRoleID(v int64) *AdminRoleMenuUpdateOne {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *AdminRoleMenuUpdateOne) SetNillableRoleID(v *int64) *AdminRoleMenuUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *AdminRoleMenuUpdateOne) AddRoleID(v int64) *AdminRoleMenuUpdateOne {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *AdminRoleMenuUpdateOne) SetMenuID(v int64) *AdminRoleMenuUpdateOne {
	_u.mutation.ResetMenuID()
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *AdminRoleMenuUpdateOne) SetNillableMenuID(v *int64) *AdminRoleMenuUpdateOne {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// AddMenuID adds value to the "menu_id" field.
func (_u *AdminRoleMenuUpdateOne) AddMenuID(v int64) *AdminRoleMenuUpdateOne {
	_u.mutation.AddMenuID(v)
	return _u
}

// Mutation returns the AdminRoleMenuMutation object of the builder.
func (_u *AdminRoleMenuUpdateOne) Mutation() *AdminRoleMenuMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminRoleMenuUpdate builder.
func (_u *AdminRoleMenuUpdateOne) Where(ps ...predicate.AdminRoleMenu) *AdminRoleMenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminRoleMenuUpdateOne) Select(field string, fields ...string) *AdminRoleMenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminRoleMenu entity.
func (_u *AdminRoleMenuUpdateOne) Save(ctx context.Context) (*AdminRoleMenu, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRoleMenuUpdateOne) SaveX(ctx context.Context) *AdminRoleMenu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminRoleMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRoleMenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AdminRoleMenuUpdateOne) sqlSave(ctx context.Context) (_node *AdminRoleMenu, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminrolemenu.Table, adminrolemenu.Columns, sqlgraph.NewFieldSpec(adminrolemenu.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminRoleMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminrolemenu.FieldID)
		for _, f := range fields {
			if !adminrolemenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminrolemenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(adminrolemenu.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(adminrolemenu.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MenuID(); ok {
		_spec.SetField(adminrolemenu.FieldMenuID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMenuID(); ok {
		_spec.AddField(adminrolemenu.FieldMenuID, field.TypeInt64, value)
	}
	_node = &AdminRoleMenu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrolemenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
