// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/adminuserrole"
)

// AdminUserRoleCreate is the builder for creating a AdminUserRole entity.
type AdminUserRoleCreate struct {
	config
	mutation *AdminUserRoleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *AdminUserRoleCreate) SetUserID(v int64) *AdminUserRoleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *AdminUserRoleCreate) SetRoleID(v int64) *AdminUserRoleCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminUserRoleCreate) SetCreatedAt(v time.Time) *AdminUserRoleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminUserRoleCreate) SetNillableCreatedAt(v *time.Time) *AdminUserRoleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AdminUserRoleMutation object of the builder.
func (_c *AdminUserRoleCreate) Mutation() *AdminUserRoleMutation {
	return _c.mutation
}

// Save creates the AdminUserRole in the database.
func (_c *AdminUserRoleCreate) Save(ctx context.Context) (*AdminUserRole, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminUserRoleCreate) SaveX(ctx context.Context) *AdminUserRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserRoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserRoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminUserRoleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminuserrole.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminUserRoleCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AdminUserRole.user_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "AdminUserRole.role_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminUserRole.created_at"`)}
	}
	return nil
}

func (_c *AdminUserRoleCreate) sqlSave(ctx context.Context) (*AdminUserRole, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminUserRoleCreate) createSpec() (*AdminUserRole, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminUserRole{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminuserrole.Table, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(adminuserrole.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(adminuserrole.FieldRoleID, field.TypeInt64, value)
		_node.RoleID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminuserrole.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminUserRole.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminUserRoleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminUserRoleCreate) OnConflict(opts ...sql.ConflictOption) *AdminUserRoleUpsertOne {
	_c.conflict = opts
	return &AdminUserRoleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminUserRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminUserRoleCreate) OnConflictColumns(columns ...string) *AdminUserRoleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminUserRoleUpsertOne{
		create: _c,
	}
}

type (
	// AdminUserRoleUpsertOne is the builder for "upsert"-ing
	//  one AdminUserRole node.
	AdminUserRoleUpsertOne struct {
		create *AdminUserRoleCreate
	}

	// AdminUserRoleUpsert is the "OnConflict" setter.
	AdminUserRoleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *AdminUserRoleUpsert) SetUserID(v int64) *AdminUserRoleUpsert {
	u.Set(adminuserrole.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminUserRoleUpsert) UpdateUserID() *AdminUserRoleUpsert {
	u.SetExcluded(adminuserrole.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AdminUserRoleUpsert) AddUserID(v int64) *AdminUserRoleUpsert {
	u.Add(adminuserrole.FieldUserID, v)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *AdminUserRoleUpsert) SetRoleID(v int64) *AdminUserRoleUpsert {
	u.Set(adminuserrole.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *AdminUserRoleUpsert) UpdateRoleID() *AdminUserRoleUpsert {
	u.SetExcluded(adminuserrole.FieldRoleID)
	return u
}

// AddRoleID adds v to the "role_id" field.
func (u *AdminUserRoleUpsert) AddRoleID(v int64) *AdminUserRoleUpsert {
	u.Add(adminuserrole.FieldRoleID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdminUserRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminUserRoleUpsertOne) UpdateNewValues() *AdminUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adminuserrole.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminUserRole.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdminUserRoleUpsertOne) Ignore() *AdminUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminUserRoleUpsertOne) DoNothing() *AdminUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminUserRoleCreate.OnConflict
// documentation for more info.
func (u *AdminUserRoleUpsertOne) Update(set func(*AdminUserRoleUpsert)) *AdminUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminUserRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdminUserRoleUpsertOne) SetUserID(v int64) *AdminUserRoleUpsertOne {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AdminUserRoleUpsertOne) AddUserID(v int64) *AdminUserRoleUpsertOne {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminUserRoleUpsertOne) UpdateUserID() *AdminUserRoleUpsertOne {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *AdminUserRoleUpsertOne) SetRoleID(v int64) *AdminUserRoleUpsertOne {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.SetRoleID(v)
	})
}

// AddRoleID adds v to the "role_id" field.
func (u *AdminUserRoleUpsertOne) AddRoleID(v int64) *AdminUserRoleUpsertOne {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.AddRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *AdminUserRoleUpsertOne) UpdateRoleID() *AdminUserRoleUpsertOne {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.UpdateRoleID()
	})
}

// Exec executes the query.
func (u *AdminUserRoleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminUserRoleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminUserRoleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdminUserRoleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdminUserRoleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdminUserRoleCreateBulk is the builder for creating many AdminUserRole entities in bulk.
type AdminUserRoleCreateBulk struct {
	config
	err      error
	builders []*AdminUserRoleCreate
	conflict []sql.ConflictOption
}

// Save creates the AdminUserRole entities in the database.
func (_c *AdminUserRoleCreateBulk) Save(ctx context.Context) ([]*AdminUserRole, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminUserRole, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminUserRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminUserRoleCreateBulk) SaveX(ctx context.Context) []*AdminUserRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserRoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminUserRole.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminUserRoleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminUserRoleCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdminUserRoleUpsertBulk {
	_c.conflict = opts
	return &AdminUserRoleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminUserRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminUserRoleCreateBulk) OnConflictColumns(columns ...string) *AdminUserRoleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminUserRoleUpsertBulk{
		create: _c,
	}
}

// AdminUserRoleUpsertBulk is the builder for "upsert"-ing
// a bulk of AdminUserRole nodes.
type AdminUserRoleUpsertBulk struct {
	create *AdminUserRoleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdminUserRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminUserRoleUpsertBulk) UpdateNewValues() *AdminUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adminuserrole.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminUserRole.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdminUserRoleUpsertBulk) Ignore() *AdminUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminUserRoleUpsertBulk) DoNothing() *AdminUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminUserRoleCreateBulk.OnConflict
// documentation for more info.
func (u *AdminUserRoleUpsertBulk) Update(set func(*AdminUserRoleUpsert)) *AdminUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminUserRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdminUserRoleUpsertBulk) SetUserID(v int64) *AdminUserRoleUpsertBulk {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AdminUserRoleUpsertBulk) AddUserID(v int64) *AdminUserRoleUpsertBulk {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminUserRoleUpsertBulk) UpdateUserID() *AdminUserRoleUpsertBulk {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *AdminUserRoleUpsertBulk) SetRoleID(v int64) *AdminUserRoleUpsertBulk {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.SetRoleID(v)
	})
}

// AddRoleID adds v to the "role_id" field.
func (u *AdminUserRoleUpsertBulk) AddRoleID(v int64) *AdminUserRoleUpsertBulk {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.AddRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *AdminUserRoleUpsertBulk) UpdateRoleID() *AdminUserRoleUpsertBulk {
	return u.Update(func(s *AdminUserRoleUpsert) {
		s.UpdateRoleID()
	})
}

// Exec executes the query.
func (u *AdminUserRoleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdminUserRoleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminUserRoleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminUserRoleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
