// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/commissionrecord"
)

// CommissionRecordCreate is the builder for creating a CommissionRecord entity.
type CommissionRecordCreate struct {
	config
	mutation *CommissionRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBeneficiaryID sets the "beneficiary_id" field.
func (_c *CommissionRecordCreate) SetBeneficiaryID(v int64) *CommissionRecordCreate {
	_c.mutation.SetBeneficiaryID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CommissionRecordCreate) SetUserID(v int64) *CommissionRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CommissionRecordCreate) SetAmount(v float64) *CommissionRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetSourceAmount sets the "source_amount" field.
func (_c *CommissionRecordCreate) SetSourceAmount(v float64) *CommissionRecordCreate {
	_c.mutation.SetSourceAmount(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CommissionRecordCreate) SetType(v string) *CommissionRecordCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *CommissionRecordCreate) SetSourceID(v int64) *CommissionRecordCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *CommissionRecordCreate) SetNillableSourceID(v *int64) *CommissionRecordCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *CommissionRecordCreate) SetNote(v string) *CommissionRecordCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *CommissionRecordCreate) SetNillableNote(v *string) *CommissionRecordCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CommissionRecordCreate) SetCreatedAt(v time.Time) *CommissionRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CommissionRecordCreate) SetNillableCreatedAt(v *time.Time) *CommissionRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CommissionRecordMutation object of the builder.
func (_c *CommissionRecordCreate) Mutation() *CommissionRecordMutation {
	return _c.mutation
}

// Save creates the CommissionRecord in the database.
func (_c *CommissionRecordCreate) Save(ctx context.Context) (*CommissionRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommissionRecordCreate) SaveX(ctx context.Context) *CommissionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommissionRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommissionRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommissionRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := commissionrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommissionRecordCreate) check() error {
	if _, ok := _c.mutation.BeneficiaryID(); !ok {
		return &ValidationError{Name: "beneficiary_id", err: errors.New(`ent: missing required field "CommissionRecord.beneficiary_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CommissionRecord.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CommissionRecord.amount"`)}
	}
	if _, ok := _c.mutation.SourceAmount(); !ok {
		return &ValidationError{Name: "source_amount", err: errors.New(`ent: missing required field "CommissionRecord.source_amount"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "CommissionRecord.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := commissionrecord.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CommissionRecord.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CommissionRecord.created_at"`)}
	}
	return nil
}

func (_c *CommissionRecordCreate) sqlSave(ctx context.Context) (*CommissionRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommissionRecordCreate) createSpec() (*CommissionRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &CommissionRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(commissionrecord.Table, sqlgraph.NewFieldSpec(commissionrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BeneficiaryID(); ok {
		_spec.SetField(commissionrecord.FieldBeneficiaryID, field.TypeInt64, value)
		_node.BeneficiaryID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(commissionrecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(commissionrecord.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.SourceAmount(); ok {
		_spec.SetField(commissionrecord.FieldSourceAmount, field.TypeFloat64, value)
		_node.SourceAmount = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(commissionrecord.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(commissionrecord.FieldSourceID, field.TypeInt64, value)
		_node.SourceID = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(commissionrecord.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(commissionrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommissionRecord.Create().
//		SetBeneficiaryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionRecordUpsert) {
//			SetBeneficiaryID(v+v).
//		}).
//		Exec(ctx)
func (_c *CommissionRecordCreate) OnConflict(opts ...sql.ConflictOption) *CommissionRecordUpsertOne {
	_c.conflict = opts
	return &CommissionRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommissionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommissionRecordCreate) OnConflictColumns(columns ...string) *CommissionRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommissionRecordUpsertOne{
		create: _c,
	}
}

type (
	// CommissionRecordUpsertOne is the builder for "upsert"-ing
	//  one CommissionRecord node.
	CommissionRecordUpsertOne struct {
		create *CommissionRecordCreate
	}

	// CommissionRecordUpsert is the "OnConflict" setter.
	CommissionRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetBeneficiaryID sets the "beneficiary_id" field.
func (u *CommissionRecordUpsert) SetBeneficiaryID(v int64) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldBeneficiaryID, v)
	return u
}

// UpdateBeneficiaryID sets the "beneficiary_id" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateBeneficiaryID() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldBeneficiaryID)
	return u
}

// AddBeneficiaryID adds v to the "beneficiary_id" field.
func (u *CommissionRecordUpsert) AddBeneficiaryID(v int64) *CommissionRecordUpsert {
	u.Add(commissionrecord.FieldBeneficiaryID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CommissionRecordUpsert) SetUserID(v int64) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateUserID() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CommissionRecordUpsert) AddUserID(v int64) *CommissionRecordUpsert {
	u.Add(commissionrecord.FieldUserID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *CommissionRecordUpsert) SetAmount(v float64) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateAmount() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CommissionRecordUpsert) AddAmount(v float64) *CommissionRecordUpsert {
	u.Add(commissionrecord.FieldAmount, v)
	return u
}

// SetSourceAmount sets the "source_amount" field.
func (u *CommissionRecordUpsert) SetSourceAmount(v float64) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldSourceAmount, v)
	return u
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateSourceAmount() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldSourceAmount)
	return u
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *CommissionRecordUpsert) AddSourceAmount(v float64) *CommissionRecordUpsert {
	u.Add(commissionrecord.FieldSourceAmount, v)
	return u
}

// SetType sets the "type" field.
func (u *CommissionRecordUpsert) SetType(v string) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateType() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *CommissionRecordUpsert) SetSourceID(v int64) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateSourceID() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *CommissionRecordUpsert) AddSourceID(v int64) *CommissionRecordUpsert {
	u.Add(commissionrecord.FieldSourceID, v)
	return u
}

// ClearSourceID clears the value of the "source_id" field.
func (u *CommissionRecordUpsert) ClearSourceID() *CommissionRecordUpsert {
	u.SetNull(commissionrecord.FieldSourceID)
	return u
}

// SetNote sets the "note" field.
func (u *CommissionRecordUpsert) SetNote(v string) *CommissionRecordUpsert {
	u.Set(commissionrecord.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CommissionRecordUpsert) UpdateNote() *CommissionRecordUpsert {
	u.SetExcluded(commissionrecord.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *CommissionRecordUpsert) ClearNote() *CommissionRecordUpsert {
	u.SetNull(commissionrecord.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CommissionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CommissionRecordUpsertOne) UpdateNewValues() *CommissionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(commissionrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommissionRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CommissionRecordUpsertOne) Ignore() *CommissionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionRecordUpsertOne) DoNothing() *CommissionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionRecordCreate.OnConflict
// documentation for more info.
func (u *CommissionRecordUpsertOne) Update(set func(*CommissionRecordUpsert)) *CommissionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetBeneficiaryID sets the "beneficiary_id" field.
func (u *CommissionRecordUpsertOne) SetBeneficiaryID(v int64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetBeneficiaryID(v)
	})
}

// AddBeneficiaryID adds v to the "beneficiary_id" field.
func (u *CommissionRecordUpsertOne) AddBeneficiaryID(v int64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddBeneficiaryID(v)
	})
}

// UpdateBeneficiaryID sets the "beneficiary_id" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateBeneficiaryID() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateBeneficiaryID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CommissionRecordUpsertOne) SetUserID(v int64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CommissionRecordUpsertOne) AddUserID(v int64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateUserID() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *CommissionRecordUpsertOne) SetAmount(v float64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CommissionRecordUpsertOne) AddAmount(v float64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateAmount() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetSourceAmount sets the "source_amount" field.
func (u *CommissionRecordUpsertOne) SetSourceAmount(v float64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetSourceAmount(v)
	})
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *CommissionRecordUpsertOne) AddSourceAmount(v float64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddSourceAmount(v)
	})
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateSourceAmount() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateSourceAmount()
	})
}

// SetType sets the "type" field.
func (u *CommissionRecordUpsertOne) SetType(v string) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateType() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *CommissionRecordUpsertOne) SetSourceID(v int64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *CommissionRecordUpsertOne) AddSourceID(v int64) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateSourceID() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *CommissionRecordUpsertOne) ClearSourceID() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.ClearSourceID()
	})
}

// SetNote sets the "note" field.
func (u *CommissionRecordUpsertOne) SetNote(v string) *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CommissionRecordUpsertOne) UpdateNote() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *CommissionRecordUpsertOne) ClearNote() *CommissionRecordUpsertOne {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *CommissionRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CommissionRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CommissionRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CommissionRecordCreateBulk is the builder for creating many CommissionRecord entities in bulk.
type CommissionRecordCreateBulk struct {
	config
	err      error
	builders []*CommissionRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the CommissionRecord entities in the database.
func (_c *CommissionRecordCreateBulk) Save(ctx context.Context) ([]*CommissionRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CommissionRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommissionRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommissionRecordCreateBulk) SaveX(ctx context.Context) []*CommissionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommissionRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommissionRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CommissionRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionRecordUpsert) {
//			SetBeneficiaryID(v+v).
//		}).
//		Exec(ctx)
func (_c *CommissionRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *CommissionRecordUpsertBulk {
	_c.conflict = opts
	return &CommissionRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CommissionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CommissionRecordCreateBulk) OnConflictColumns(columns ...string) *CommissionRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CommissionRecordUpsertBulk{
		create: _c,
	}
}

// CommissionRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of CommissionRecord nodes.
type CommissionRecordUpsertBulk struct {
	create *CommissionRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CommissionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CommissionRecordUpsertBulk) UpdateNewValues() *CommissionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(commissionrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CommissionRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CommissionRecordUpsertBulk) Ignore() *CommissionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionRecordUpsertBulk) DoNothing() *CommissionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionRecordCreateBulk.OnConflict
// documentation for more info.
func (u *CommissionRecordUpsertBulk) Update(set func(*CommissionRecordUpsert)) *CommissionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetBeneficiaryID sets the "beneficiary_id" field.
func (u *CommissionRecordUpsertBulk) SetBeneficiaryID(v int64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetBeneficiaryID(v)
	})
}

// AddBeneficiaryID adds v to the "beneficiary_id" field.
func (u *CommissionRecordUpsertBulk) AddBeneficiaryID(v int64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddBeneficiaryID(v)
	})
}

// UpdateBeneficiaryID sets the "beneficiary_id" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateBeneficiaryID() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateBeneficiaryID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CommissionRecordUpsertBulk) SetUserID(v int64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CommissionRecordUpsertBulk) AddUserID(v int64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateUserID() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *CommissionRecordUpsertBulk) SetAmount(v float64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CommissionRecordUpsertBulk) AddAmount(v float64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateAmount() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetSourceAmount sets the "source_amount" field.
func (u *CommissionRecordUpsertBulk) SetSourceAmount(v float64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetSourceAmount(v)
	})
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *CommissionRecordUpsertBulk) AddSourceAmount(v float64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddSourceAmount(v)
	})
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateSourceAmount() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateSourceAmount()
	})
}

// SetType sets the "type" field.
func (u *CommissionRecordUpsertBulk) SetType(v string) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateType() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *CommissionRecordUpsertBulk) SetSourceID(v int64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *CommissionRecordUpsertBulk) AddSourceID(v int64) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateSourceID() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *CommissionRecordUpsertBulk) ClearSourceID() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.ClearSourceID()
	})
}

// SetNote sets the "note" field.
func (u *CommissionRecordUpsertBulk) SetNote(v string) *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *CommissionRecordUpsertBulk) UpdateNote() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *CommissionRecordUpsertBulk) ClearNote() *CommissionRecordUpsertBulk {
	return u.Update(func(s *CommissionRecordUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *CommissionRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CommissionRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
