// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedback"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedbackreply"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
)

// FeedbackUpdate is the builder for updating Feedback entities.
type FeedbackUpdate struct {
	config
	hooks    []Hook
	mutation *FeedbackMutation
}

// Where appends a list predicates to the FeedbackUpdate builder.
func (_u *FeedbackUpdate) Where(ps ...predicate.Feedback) *FeedbackUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FeedbackUpdate) SetDeletedAt(v time.Time) *FeedbackUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableDeletedAt(v *time.Time) *FeedbackUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FeedbackUpdate) ClearDeletedAt() *FeedbackUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FeedbackUpdate) SetUserID(v int64) *FeedbackUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableUserID(v *int64) *FeedbackUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *FeedbackUpdate) SetCategory(v string) *FeedbackUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableCategory(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *FeedbackUpdate) SetTitle(v string) *FeedbackUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableTitle(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *FeedbackUpdate) SetContent(v string) *FeedbackUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableContent(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetImages sets the "images" field.
func (_u *FeedbackUpdate) SetImages(v []string) *FeedbackUpdate {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *FeedbackUpdate) AppendImages(v []string) *FeedbackUpdate {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *FeedbackUpdate) ClearImages() *FeedbackUpdate {
	_u.mutation.ClearImages()
	return _u
}

// SetContact sets the "contact" field.
func (_u *FeedbackUpdate) SetContact(v string) *FeedbackUpdate {
	_u.mutation.SetContact(v)
	return _u
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableContact(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetContact(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *FeedbackUpdate) SetPriority(v string) *FeedbackUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillablePriority(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FeedbackUpdate) SetStatus(v string) *FeedbackUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableStatus(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReplyCount sets the "reply_count" field.
func (_u *FeedbackUpdate) SetReplyCount(v int) *FeedbackUpdate {
	_u.mutation.ResetReplyCount()
	_u.mutation.SetReplyCount(v)
	return _u
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableReplyCount(v *int) *FeedbackUpdate {
	if v != nil {
		_u.SetReplyCount(*v)
	}
	return _u
}

// AddReplyCount adds value to the "reply_count" field.
func (_u *FeedbackUpdate) AddReplyCount(v int) *FeedbackUpdate {
	_u.mutation.AddReplyCount(v)
	return _u
}

// SetLastReplyAt sets the "last_reply_at" field.
func (_u *FeedbackUpdate) SetLastReplyAt(v time.Time) *FeedbackUpdate {
	_u.mutation.SetLastReplyAt(v)
	return _u
}

// SetNillableLastReplyAt sets the "last_reply_at" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableLastReplyAt(v *time.Time) *FeedbackUpdate {
	if v != nil {
		_u.SetLastReplyAt(*v)
	}
	return _u
}

// ClearLastReplyAt clears the value of the "last_reply_at" field.
func (_u *FeedbackUpdate) ClearLastReplyAt() *FeedbackUpdate {
	_u.mutation.ClearLastReplyAt()
	return _u
}

// SetLastReplyRole sets the "last_reply_role" field.
func (_u *FeedbackUpdate) SetLastReplyRole(v string) *FeedbackUpdate {
	_u.mutation.SetLastReplyRole(v)
	return _u
}

// SetNillableLastReplyRole sets the "last_reply_role" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableLastReplyRole(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetLastReplyRole(*v)
	}
	return _u
}

// ClearLastReplyRole clears the value of the "last_reply_role" field.
func (_u *FeedbackUpdate) ClearLastReplyRole() *FeedbackUpdate {
	_u.mutation.ClearLastReplyRole()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedbackUpdate) SetUpdatedAt(v time.Time) *FeedbackUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *FeedbackUpdate) SetUser(v *User) *FeedbackUpdate {
	return _u.SetUserID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the FeedbackReply entity by IDs.
func (_u *FeedbackUpdate) AddReplyIDs(ids ...int64) *FeedbackUpdate {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the FeedbackReply entity.
func (_u *FeedbackUpdate) AddReplies(v ...*FeedbackReply) *FeedbackUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// Mutation returns the FeedbackMutation object of the builder.
func (_u *FeedbackUpdate) Mutation() *FeedbackMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FeedbackUpdate) ClearUser() *FeedbackUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearReplies clears all "replies" edges to the FeedbackReply entity.
func (_u *FeedbackUpdate) ClearReplies() *FeedbackUpdate {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to FeedbackReply entities by IDs.
func (_u *FeedbackUpdate) RemoveReplyIDs(ids ...int64) *FeedbackUpdate {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to FeedbackReply entities.
func (_u *FeedbackUpdate) RemoveReplies(v ...*FeedbackReply) *FeedbackUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeedbackUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeedbackUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedbackUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if feedback.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized feedback.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := feedback.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := feedback.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Feedback.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := feedback.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Feedback.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := feedback.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Feedback.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Contact(); ok {
		if err := feedback.ContactValidator(v); err != nil {
			return &ValidationError{Name: "contact", err: fmt.Errorf(`ent: validator failed for field "Feedback.contact": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := feedback.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Feedback.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := feedback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Feedback.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastReplyRole(); ok {
		if err := feedback.LastReplyRoleValidator(v); err != nil {
			return &ValidationError{Name: "last_reply_role", err: fmt.Errorf(`ent: validator failed for field "Feedback.last_reply_role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Feedback.user"`)
	}
	return nil
}

func (_u *FeedbackUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedback.Table, feedback.Columns, sqlgraph.NewFieldSpec(feedback.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(feedback.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(feedback.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(feedback.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(feedback.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(feedback.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(feedback.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, feedback.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(feedback.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Contact(); ok {
		_spec.SetField(feedback.FieldContact, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(feedback.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(feedback.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReplyCount(); ok {
		_spec.SetField(feedback.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyCount(); ok {
		_spec.AddField(feedback.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastReplyAt(); ok {
		_spec.SetField(feedback.FieldLastReplyAt, field.TypeTime, value)
	}
	if _u.mutation.LastReplyAtCleared() {
		_spec.ClearField(feedback.FieldLastReplyAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReplyRole(); ok {
		_spec.SetField(feedback.FieldLastReplyRole, field.TypeString, value)
	}
	if _u.mutation.LastReplyRoleCleared() {
		_spec.ClearField(feedback.FieldLastReplyRole, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feedback.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feedback.UserTable,
			Columns: []string{feedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feedback.UserTable,
			Columns: []string{feedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feedback.RepliesTable,
			Columns: []string{feedback.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feedback.RepliesTable,
			Columns: []string{feedback.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feedback.RepliesTable,
			Columns: []string{feedback.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeedbackUpdateOne is the builder for updating a single Feedback entity.
type FeedbackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeedbackMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FeedbackUpdateOne) SetDeletedAt(v time.Time) *FeedbackUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableDeletedAt(v *time.Time) *FeedbackUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FeedbackUpdateOne) ClearDeletedAt() *FeedbackUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FeedbackUpdateOne) SetUserID(v int64) *FeedbackUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableUserID(v *int64) *FeedbackUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *FeedbackUpdateOne) SetCategory(v string) *FeedbackUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableCategory(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *FeedbackUpdateOne) SetTitle(v string) *FeedbackUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableTitle(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *FeedbackUpdateOne) SetContent(v string) *FeedbackUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableContent(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetImages sets the "images" field.
func (_u *FeedbackUpdateOne) SetImages(v []string) *FeedbackUpdateOne {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *FeedbackUpdateOne) AppendImages(v []string) *FeedbackUpdateOne {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *FeedbackUpdateOne) ClearImages() *FeedbackUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// SetContact sets the "contact" field.
func (_u *FeedbackUpdateOne) SetContact(v string) *FeedbackUpdateOne {
	_u.mutation.SetContact(v)
	return _u
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableContact(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetContact(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *FeedbackUpdateOne) SetPriority(v string) *FeedbackUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillablePriority(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FeedbackUpdateOne) SetStatus(v string) *FeedbackUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableStatus(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReplyCount sets the "reply_count" field.
func (_u *FeedbackUpdateOne) SetReplyCount(v int) *FeedbackUpdateOne {
	_u.mutation.ResetReplyCount()
	_u.mutation.SetReplyCount(v)
	return _u
}

// SetNillableReplyCount sets the "reply_count" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableReplyCount(v *int) *FeedbackUpdateOne {
	if v != nil {
		_u.SetReplyCount(*v)
	}
	return _u
}

// AddReplyCount adds value to the "reply_count" field.
func (_u *FeedbackUpdateOne) AddReplyCount(v int) *FeedbackUpdateOne {
	_u.mutation.AddReplyCount(v)
	return _u
}

// SetLastReplyAt sets the "last_reply_at" field.
func (_u *FeedbackUpdateOne) SetLastReplyAt(v time.Time) *FeedbackUpdateOne {
	_u.mutation.SetLastReplyAt(v)
	return _u
}

// SetNillableLastReplyAt sets the "last_reply_at" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableLastReplyAt(v *time.Time) *FeedbackUpdateOne {
	if v != nil {
		_u.SetLastReplyAt(*v)
	}
	return _u
}

// ClearLastReplyAt clears the value of the "last_reply_at" field.
func (_u *FeedbackUpdateOne) ClearLastReplyAt() *FeedbackUpdateOne {
	_u.mutation.ClearLastReplyAt()
	return _u
}

// SetLastReplyRole sets the "last_reply_role" field.
func (_u *FeedbackUpdateOne) SetLastReplyRole(v string) *FeedbackUpdateOne {
	_u.mutation.SetLastReplyRole(v)
	return _u
}

// SetNillableLastReplyRole sets the "last_reply_role" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableLastReplyRole(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetLastReplyRole(*v)
	}
	return _u
}

// ClearLastReplyRole clears the value of the "last_reply_role" field.
func (_u *FeedbackUpdateOne) ClearLastReplyRole() *FeedbackUpdateOne {
	_u.mutation.ClearLastReplyRole()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedbackUpdateOne) SetUpdatedAt(v time.Time) *FeedbackUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *FeedbackUpdateOne) SetUser(v *User) *FeedbackUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the FeedbackReply entity by IDs.
func (_u *FeedbackUpdateOne) AddReplyIDs(ids ...int64) *FeedbackUpdateOne {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the FeedbackReply entity.
func (_u *FeedbackUpdateOne) AddReplies(v ...*FeedbackReply) *FeedbackUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// Mutation returns the FeedbackMutation object of the builder.
func (_u *FeedbackUpdateOne) Mutation() *FeedbackMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FeedbackUpdateOne) ClearUser() *FeedbackUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearReplies clears all "replies" edges to the FeedbackReply entity.
func (_u *FeedbackUpdateOne) ClearReplies() *FeedbackUpdateOne {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to FeedbackReply entities by IDs.
func (_u *FeedbackUpdateOne) RemoveReplyIDs(ids ...int64) *FeedbackUpdateOne {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to FeedbackReply entities.
func (_u *FeedbackUpdateOne) RemoveReplies(v ...*FeedbackReply) *FeedbackUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// Where appends a list predicates to the FeedbackUpdate builder.
func (_u *FeedbackUpdateOne) Where(ps ...predicate.Feedback) *FeedbackUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeedbackUpdateOne) Select(field string, fields ...string) *FeedbackUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Feedback entity.
func (_u *FeedbackUpdateOne) Save(ctx context.Context) (*Feedback, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackUpdateOne) SaveX(ctx context.Context) *Feedback {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeedbackUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedbackUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if feedback.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized feedback.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := feedback.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := feedback.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Feedback.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := feedback.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Feedback.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := feedback.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Feedback.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Contact(); ok {
		if err := feedback.ContactValidator(v); err != nil {
			return &ValidationError{Name: "contact", err: fmt.Errorf(`ent: validator failed for field "Feedback.contact": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := feedback.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Feedback.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := feedback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Feedback.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastReplyRole(); ok {
		if err := feedback.LastReplyRoleValidator(v); err != nil {
			return &ValidationError{Name: "last_reply_role", err: fmt.Errorf(`ent: validator failed for field "Feedback.last_reply_role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Feedback.user"`)
	}
	return nil
}

func (_u *FeedbackUpdateOne) sqlSave(ctx context.Context) (_node *Feedback, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedback.Table, feedback.Columns, sqlgraph.NewFieldSpec(feedback.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Feedback.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedback.FieldID)
		for _, f := range fields {
			if !feedback.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feedback.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(feedback.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(feedback.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(feedback.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(feedback.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(feedback.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(feedback.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, feedback.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(feedback.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Contact(); ok {
		_spec.SetField(feedback.FieldContact, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(feedback.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(feedback.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReplyCount(); ok {
		_spec.SetField(feedback.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReplyCount(); ok {
		_spec.AddField(feedback.FieldReplyCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastReplyAt(); ok {
		_spec.SetField(feedback.FieldLastReplyAt, field.TypeTime, value)
	}
	if _u.mutation.LastReplyAtCleared() {
		_spec.ClearField(feedback.FieldLastReplyAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReplyRole(); ok {
		_spec.SetField(feedback.FieldLastReplyRole, field.TypeString, value)
	}
	if _u.mutation.LastReplyRoleCleared() {
		_spec.ClearField(feedback.FieldLastReplyRole, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feedback.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feedback.UserTable,
			Columns: []string{feedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   feedback.UserTable,
			Columns: []string{feedback.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feedback.RepliesTable,
			Columns: []string{feedback.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feedback.RepliesTable,
			Columns: []string{feedback.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feedback.RepliesTable,
			Columns: []string{feedback.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Feedback{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
