// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedback"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
)

// Feedback is the model entity for the Feedback schema.
type Feedback struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Images holds the value of the "images" field.
	Images []string `json:"images,omitempty"`
	// Contact holds the value of the "contact" field.
	Contact string `json:"contact,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TriageStatus holds the value of the "triage_status" field.
	TriageStatus string `json:"triage_status,omitempty"`
	// TriagePriority holds the value of the "triage_priority" field.
	TriagePriority string `json:"triage_priority,omitempty"`
	// TriageSummary holds the value of the "triage_summary" field.
	TriageSummary string `json:"triage_summary,omitempty"`
	// TriageConfidence holds the value of the "triage_confidence" field.
	TriageConfidence *float64 `json:"triage_confidence,omitempty"`
	// RepairDifficulty holds the value of the "repair_difficulty" field.
	RepairDifficulty string `json:"repair_difficulty,omitempty"`
	// RepairRecommendation holds the value of the "repair_recommendation" field.
	RepairRecommendation string `json:"repair_recommendation,omitempty"`
	// OwnerDecision holds the value of the "owner_decision" field.
	OwnerDecision string `json:"owner_decision,omitempty"`
	// FixStatus holds the value of the "fix_status" field.
	FixStatus string `json:"fix_status,omitempty"`
	// DuplicateOfID holds the value of the "duplicate_of_id" field.
	DuplicateOfID *int64 `json:"duplicate_of_id,omitempty"`
	// ResolvedVersion holds the value of the "resolved_version" field.
	ResolvedVersion string `json:"resolved_version,omitempty"`
	// ReplyCount holds the value of the "reply_count" field.
	ReplyCount int `json:"reply_count,omitempty"`
	// LastReplyAt holds the value of the "last_reply_at" field.
	LastReplyAt *time.Time `json:"last_reply_at,omitempty"`
	// LastReplyRole holds the value of the "last_reply_role" field.
	LastReplyRole *string `json:"last_reply_role,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FeedbackQuery when eager-loading is set.
	Edges        FeedbackEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FeedbackEdges holds the relations/edges for other nodes in the graph.
type FeedbackEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Replies holds the value of the replies edge.
	Replies []*FeedbackReply `json:"replies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FeedbackEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RepliesOrErr returns the Replies value or an error if the edge
// was not loaded in eager-loading.
func (e FeedbackEdges) RepliesOrErr() ([]*FeedbackReply, error) {
	if e.loadedTypes[1] {
		return e.Replies, nil
	}
	return nil, &NotLoadedError{edge: "replies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Feedback) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case feedback.FieldImages:
			values[i] = new([]byte)
		case feedback.FieldTriageConfidence:
			values[i] = new(sql.NullFloat64)
		case feedback.FieldID, feedback.FieldUserID, feedback.FieldDuplicateOfID, feedback.FieldReplyCount:
			values[i] = new(sql.NullInt64)
		case feedback.FieldCategory, feedback.FieldTitle, feedback.FieldContent, feedback.FieldContact, feedback.FieldRequestID, feedback.FieldPriority, feedback.FieldStatus, feedback.FieldTriageStatus, feedback.FieldTriagePriority, feedback.FieldTriageSummary, feedback.FieldRepairDifficulty, feedback.FieldRepairRecommendation, feedback.FieldOwnerDecision, feedback.FieldFixStatus, feedback.FieldResolvedVersion, feedback.FieldLastReplyRole:
			values[i] = new(sql.NullString)
		case feedback.FieldDeletedAt, feedback.FieldLastReplyAt, feedback.FieldAcceptedAt, feedback.FieldResolvedAt, feedback.FieldVerifiedAt, feedback.FieldCreatedAt, feedback.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Feedback fields.
func (_m *Feedback) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case feedback.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case feedback.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case feedback.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case feedback.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case feedback.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case feedback.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case feedback.FieldImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Images); err != nil {
					return fmt.Errorf("unmarshal field images: %w", err)
				}
			}
		case feedback.FieldContact:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact", values[i])
			} else if value.Valid {
				_m.Contact = value.String
			}
		case feedback.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case feedback.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case feedback.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case feedback.FieldTriageStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field triage_status", values[i])
			} else if value.Valid {
				_m.TriageStatus = value.String
			}
		case feedback.FieldTriagePriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field triage_priority", values[i])
			} else if value.Valid {
				_m.TriagePriority = value.String
			}
		case feedback.FieldTriageSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field triage_summary", values[i])
			} else if value.Valid {
				_m.TriageSummary = value.String
			}
		case feedback.FieldTriageConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field triage_confidence", values[i])
			} else if value.Valid {
				_m.TriageConfidence = new(float64)
				*_m.TriageConfidence = value.Float64
			}
		case feedback.FieldRepairDifficulty:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repair_difficulty", values[i])
			} else if value.Valid {
				_m.RepairDifficulty = value.String
			}
		case feedback.FieldRepairRecommendation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repair_recommendation", values[i])
			} else if value.Valid {
				_m.RepairRecommendation = value.String
			}
		case feedback.FieldOwnerDecision:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_decision", values[i])
			} else if value.Valid {
				_m.OwnerDecision = value.String
			}
		case feedback.FieldFixStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fix_status", values[i])
			} else if value.Valid {
				_m.FixStatus = value.String
			}
		case feedback.FieldDuplicateOfID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_of_id", values[i])
			} else if value.Valid {
				_m.DuplicateOfID = new(int64)
				*_m.DuplicateOfID = value.Int64
			}
		case feedback.FieldResolvedVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_version", values[i])
			} else if value.Valid {
				_m.ResolvedVersion = value.String
			}
		case feedback.FieldReplyCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reply_count", values[i])
			} else if value.Valid {
				_m.ReplyCount = int(value.Int64)
			}
		case feedback.FieldLastReplyAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_reply_at", values[i])
			} else if value.Valid {
				_m.LastReplyAt = new(time.Time)
				*_m.LastReplyAt = value.Time
			}
		case feedback.FieldLastReplyRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_reply_role", values[i])
			} else if value.Valid {
				_m.LastReplyRole = new(string)
				*_m.LastReplyRole = value.String
			}
		case feedback.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		case feedback.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case feedback.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = new(time.Time)
				*_m.VerifiedAt = value.Time
			}
		case feedback.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case feedback.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Feedback.
// This includes values selected through modifiers, order, etc.
func (_m *Feedback) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Feedback entity.
func (_m *Feedback) QueryUser() *UserQuery {
	return NewFeedbackClient(_m.config).QueryUser(_m)
}

// QueryReplies queries the "replies" edge of the Feedback entity.
func (_m *Feedback) QueryReplies() *FeedbackReplyQuery {
	return NewFeedbackClient(_m.config).QueryReplies(_m)
}

// Update returns a builder for updating this Feedback.
// Note that you need to call Feedback.Unwrap() before calling this method if this Feedback
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Feedback) Update() *FeedbackUpdateOne {
	return NewFeedbackClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Feedback entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Feedback) Unwrap() *Feedback {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Feedback is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Feedback) String() string {
	var builder strings.Builder
	builder.WriteString("Feedback(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("images=")
	builder.WriteString(fmt.Sprintf("%v", _m.Images))
	builder.WriteString(", ")
	builder.WriteString("contact=")
	builder.WriteString(_m.Contact)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("triage_status=")
	builder.WriteString(_m.TriageStatus)
	builder.WriteString(", ")
	builder.WriteString("triage_priority=")
	builder.WriteString(_m.TriagePriority)
	builder.WriteString(", ")
	builder.WriteString("triage_summary=")
	builder.WriteString(_m.TriageSummary)
	builder.WriteString(", ")
	if v := _m.TriageConfidence; v != nil {
		builder.WriteString("triage_confidence=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("repair_difficulty=")
	builder.WriteString(_m.RepairDifficulty)
	builder.WriteString(", ")
	builder.WriteString("repair_recommendation=")
	builder.WriteString(_m.RepairRecommendation)
	builder.WriteString(", ")
	builder.WriteString("owner_decision=")
	builder.WriteString(_m.OwnerDecision)
	builder.WriteString(", ")
	builder.WriteString("fix_status=")
	builder.WriteString(_m.FixStatus)
	builder.WriteString(", ")
	if v := _m.DuplicateOfID; v != nil {
		builder.WriteString("duplicate_of_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("resolved_version=")
	builder.WriteString(_m.ResolvedVersion)
	builder.WriteString(", ")
	builder.WriteString("reply_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReplyCount))
	builder.WriteString(", ")
	if v := _m.LastReplyAt; v != nil {
		builder.WriteString("last_reply_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastReplyRole; v != nil {
		builder.WriteString("last_reply_role=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Feedbacks is a parsable slice of Feedback.
type Feedbacks []*Feedback
