// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedbackevent"
)

// FeedbackEvent is the model entity for the FeedbackEvent schema.
type FeedbackEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// FeedbackID holds the value of the "feedback_id" field.
	FeedbackID int64 `json:"feedback_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// ActorType holds the value of the "actor_type" field.
	ActorType string `json:"actor_type,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID *int64 `json:"actor_user_id,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FeedbackEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case feedbackevent.FieldMetadata:
			values[i] = new([]byte)
		case feedbackevent.FieldID, feedbackevent.FieldFeedbackID, feedbackevent.FieldActorUserID:
			values[i] = new(sql.NullInt64)
		case feedbackevent.FieldEventType, feedbackevent.FieldActorType, feedbackevent.FieldSummary:
			values[i] = new(sql.NullString)
		case feedbackevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FeedbackEvent fields.
func (_m *FeedbackEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case feedbackevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case feedbackevent.FieldFeedbackID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feedback_id", values[i])
			} else if value.Valid {
				_m.FeedbackID = value.Int64
			}
		case feedbackevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case feedbackevent.FieldActorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_type", values[i])
			} else if value.Valid {
				_m.ActorType = value.String
			}
		case feedbackevent.FieldActorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = new(int64)
				*_m.ActorUserID = value.Int64
			}
		case feedbackevent.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case feedbackevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case feedbackevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FeedbackEvent.
// This includes values selected through modifiers, order, etc.
func (_m *FeedbackEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FeedbackEvent.
// Note that you need to call FeedbackEvent.Unwrap() before calling this method if this FeedbackEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FeedbackEvent) Update() *FeedbackEventUpdateOne {
	return NewFeedbackEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FeedbackEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FeedbackEvent) Unwrap() *FeedbackEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FeedbackEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FeedbackEvent) String() string {
	var builder strings.Builder
	builder.WriteString("FeedbackEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("feedback_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeedbackID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("actor_type=")
	builder.WriteString(_m.ActorType)
	builder.WriteString(", ")
	if v := _m.ActorUserID; v != nil {
		builder.WriteString("actor_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FeedbackEvents is a parsable slice of FeedbackEvent.
type FeedbackEvents []*FeedbackEvent
