// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedback"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedbackreply"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
)

// FeedbackReply is the model entity for the FeedbackReply schema.
type FeedbackReply struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// FeedbackID holds the value of the "feedback_id" field.
	FeedbackID int64 `json:"feedback_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Images holds the value of the "images" field.
	Images []string `json:"images,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FeedbackReplyQuery when eager-loading is set.
	Edges        FeedbackReplyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FeedbackReplyEdges holds the relations/edges for other nodes in the graph.
type FeedbackReplyEdges struct {
	// Feedback holds the value of the feedback edge.
	Feedback *Feedback `json:"feedback,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FeedbackOrErr returns the Feedback value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FeedbackReplyEdges) FeedbackOrErr() (*Feedback, error) {
	if e.Feedback != nil {
		return e.Feedback, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: feedback.Label}
	}
	return nil, &NotLoadedError{edge: "feedback"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FeedbackReplyEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FeedbackReply) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case feedbackreply.FieldImages:
			values[i] = new([]byte)
		case feedbackreply.FieldID, feedbackreply.FieldFeedbackID, feedbackreply.FieldUserID:
			values[i] = new(sql.NullInt64)
		case feedbackreply.FieldRole, feedbackreply.FieldContent:
			values[i] = new(sql.NullString)
		case feedbackreply.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FeedbackReply fields.
func (_m *FeedbackReply) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case feedbackreply.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case feedbackreply.FieldFeedbackID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feedback_id", values[i])
			} else if value.Valid {
				_m.FeedbackID = value.Int64
			}
		case feedbackreply.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case feedbackreply.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case feedbackreply.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case feedbackreply.FieldImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Images); err != nil {
					return fmt.Errorf("unmarshal field images: %w", err)
				}
			}
		case feedbackreply.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FeedbackReply.
// This includes values selected through modifiers, order, etc.
func (_m *FeedbackReply) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFeedback queries the "feedback" edge of the FeedbackReply entity.
func (_m *FeedbackReply) QueryFeedback() *FeedbackQuery {
	return NewFeedbackReplyClient(_m.config).QueryFeedback(_m)
}

// QueryUser queries the "user" edge of the FeedbackReply entity.
func (_m *FeedbackReply) QueryUser() *UserQuery {
	return NewFeedbackReplyClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this FeedbackReply.
// Note that you need to call FeedbackReply.Unwrap() before calling this method if this FeedbackReply
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FeedbackReply) Update() *FeedbackReplyUpdateOne {
	return NewFeedbackReplyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FeedbackReply entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FeedbackReply) Unwrap() *FeedbackReply {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FeedbackReply is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FeedbackReply) String() string {
	var builder strings.Builder
	builder.WriteString("FeedbackReply(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("feedback_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeedbackID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("images=")
	builder.WriteString(fmt.Sprintf("%v", _m.Images))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FeedbackReplies is a parsable slice of FeedbackReply.
type FeedbackReplies []*FeedbackReply
