// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedbackreward"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// FeedbackRewardUpdate is the builder for updating FeedbackReward entities.
type FeedbackRewardUpdate struct {
	config
	hooks    []Hook
	mutation *FeedbackRewardMutation
}

// Where appends a list predicates to the FeedbackRewardUpdate builder.
func (_u *FeedbackRewardUpdate) Where(ps ...predicate.FeedbackReward) *FeedbackRewardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFeedbackID sets the "feedback_id" field.
func (_u *FeedbackRewardUpdate) SetFeedbackID(v int64) *FeedbackRewardUpdate {
	_u.mutation.ResetFeedbackID()
	_u.mutation.SetFeedbackID(v)
	return _u
}

// SetNillableFeedbackID sets the "feedback_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableFeedbackID(v *int64) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetFeedbackID(*v)
	}
	return _u
}

// AddFeedbackID adds value to the "feedback_id" field.
func (_u *FeedbackRewardUpdate) AddFeedbackID(v int64) *FeedbackRewardUpdate {
	_u.mutation.AddFeedbackID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FeedbackRewardUpdate) SetUserID(v int64) *FeedbackRewardUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableUserID(v *int64) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *FeedbackRewardUpdate) AddUserID(v int64) *FeedbackRewardUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *FeedbackRewardUpdate) SetAmount(v float64) *FeedbackRewardUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableAmount(v *float64) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *FeedbackRewardUpdate) AddAmount(v float64) *FeedbackRewardUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *FeedbackRewardUpdate) SetReason(v string) *FeedbackRewardUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableReason(v *string) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *FeedbackRewardUpdate) SetBatchID(v string) *FeedbackRewardUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableBatchID(v *string) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *FeedbackRewardUpdate) SetOperatorUserID(v int64) *FeedbackRewardUpdate {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableOperatorUserID(v *int64) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *FeedbackRewardUpdate) AddOperatorUserID(v int64) *FeedbackRewardUpdate {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *FeedbackRewardUpdate) ClearOperatorUserID() *FeedbackRewardUpdate {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetAccountChangeRecordID sets the "account_change_record_id" field.
func (_u *FeedbackRewardUpdate) SetAccountChangeRecordID(v int64) *FeedbackRewardUpdate {
	_u.mutation.ResetAccountChangeRecordID()
	_u.mutation.SetAccountChangeRecordID(v)
	return _u
}

// SetNillableAccountChangeRecordID sets the "account_change_record_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableAccountChangeRecordID(v *int64) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetAccountChangeRecordID(*v)
	}
	return _u
}

// AddAccountChangeRecordID adds value to the "account_change_record_id" field.
func (_u *FeedbackRewardUpdate) AddAccountChangeRecordID(v int64) *FeedbackRewardUpdate {
	_u.mutation.AddAccountChangeRecordID(v)
	return _u
}

// ClearAccountChangeRecordID clears the value of the "account_change_record_id" field.
func (_u *FeedbackRewardUpdate) ClearAccountChangeRecordID() *FeedbackRewardUpdate {
	_u.mutation.ClearAccountChangeRecordID()
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *FeedbackRewardUpdate) SetGrantedAt(v time.Time) *FeedbackRewardUpdate {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *FeedbackRewardUpdate) SetNillableGrantedAt(v *time.Time) *FeedbackRewardUpdate {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// Mutation returns the FeedbackRewardMutation object of the builder.
func (_u *FeedbackRewardUpdate) Mutation() *FeedbackRewardMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeedbackRewardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackRewardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeedbackRewardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackRewardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackRewardUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := feedbackreward.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "FeedbackReward.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BatchID(); ok {
		if err := feedbackreward.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackReward.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedbackRewardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedbackreward.Table, feedbackreward.Columns, sqlgraph.NewFieldSpec(feedbackreward.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FeedbackID(); ok {
		_spec.SetField(feedbackreward.FieldFeedbackID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFeedbackID(); ok {
		_spec.AddField(feedbackreward.FieldFeedbackID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(feedbackreward.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(feedbackreward.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(feedbackreward.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(feedbackreward.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(feedbackreward.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(feedbackreward.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(feedbackreward.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(feedbackreward.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(feedbackreward.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountChangeRecordID(); ok {
		_spec.SetField(feedbackreward.FieldAccountChangeRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountChangeRecordID(); ok {
		_spec.AddField(feedbackreward.FieldAccountChangeRecordID, field.TypeInt64, value)
	}
	if _u.mutation.AccountChangeRecordIDCleared() {
		_spec.ClearField(feedbackreward.FieldAccountChangeRecordID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(feedbackreward.FieldGrantedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedbackreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeedbackRewardUpdateOne is the builder for updating a single FeedbackReward entity.
type FeedbackRewardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeedbackRewardMutation
}

// SetFeedbackID sets the "feedback_id" field.
func (_u *FeedbackRewardUpdateOne) SetFeedbackID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.ResetFeedbackID()
	_u.mutation.SetFeedbackID(v)
	return _u
}

// SetNillableFeedbackID sets the "feedback_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableFeedbackID(v *int64) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetFeedbackID(*v)
	}
	return _u
}

// AddFeedbackID adds value to the "feedback_id" field.
func (_u *FeedbackRewardUpdateOne) AddFeedbackID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.AddFeedbackID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FeedbackRewardUpdateOne) SetUserID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableUserID(v *int64) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *FeedbackRewardUpdateOne) AddUserID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *FeedbackRewardUpdateOne) SetAmount(v float64) *FeedbackRewardUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableAmount(v *float64) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *FeedbackRewardUpdateOne) AddAmount(v float64) *FeedbackRewardUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *FeedbackRewardUpdateOne) SetReason(v string) *FeedbackRewardUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableReason(v *string) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *FeedbackRewardUpdateOne) SetBatchID(v string) *FeedbackRewardUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableBatchID(v *string) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *FeedbackRewardUpdateOne) SetOperatorUserID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.ResetOperatorUserID()
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableOperatorUserID(v *int64) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// AddOperatorUserID adds value to the "operator_user_id" field.
func (_u *FeedbackRewardUpdateOne) AddOperatorUserID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.AddOperatorUserID(v)
	return _u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (_u *FeedbackRewardUpdateOne) ClearOperatorUserID() *FeedbackRewardUpdateOne {
	_u.mutation.ClearOperatorUserID()
	return _u
}

// SetAccountChangeRecordID sets the "account_change_record_id" field.
func (_u *FeedbackRewardUpdateOne) SetAccountChangeRecordID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.ResetAccountChangeRecordID()
	_u.mutation.SetAccountChangeRecordID(v)
	return _u
}

// SetNillableAccountChangeRecordID sets the "account_change_record_id" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableAccountChangeRecordID(v *int64) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetAccountChangeRecordID(*v)
	}
	return _u
}

// AddAccountChangeRecordID adds value to the "account_change_record_id" field.
func (_u *FeedbackRewardUpdateOne) AddAccountChangeRecordID(v int64) *FeedbackRewardUpdateOne {
	_u.mutation.AddAccountChangeRecordID(v)
	return _u
}

// ClearAccountChangeRecordID clears the value of the "account_change_record_id" field.
func (_u *FeedbackRewardUpdateOne) ClearAccountChangeRecordID() *FeedbackRewardUpdateOne {
	_u.mutation.ClearAccountChangeRecordID()
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *FeedbackRewardUpdateOne) SetGrantedAt(v time.Time) *FeedbackRewardUpdateOne {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *FeedbackRewardUpdateOne) SetNillableGrantedAt(v *time.Time) *FeedbackRewardUpdateOne {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// Mutation returns the FeedbackRewardMutation object of the builder.
func (_u *FeedbackRewardUpdateOne) Mutation() *FeedbackRewardMutation {
	return _u.mutation
}

// Where appends a list predicates to the FeedbackRewardUpdate builder.
func (_u *FeedbackRewardUpdateOne) Where(ps ...predicate.FeedbackReward) *FeedbackRewardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeedbackRewardUpdateOne) Select(field string, fields ...string) *FeedbackRewardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FeedbackReward entity.
func (_u *FeedbackRewardUpdateOne) Save(ctx context.Context) (*FeedbackReward, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackRewardUpdateOne) SaveX(ctx context.Context) *FeedbackReward {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeedbackRewardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackRewardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackRewardUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := feedbackreward.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "FeedbackReward.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BatchID(); ok {
		if err := feedbackreward.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackReward.batch_id": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedbackRewardUpdateOne) sqlSave(ctx context.Context) (_node *FeedbackReward, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedbackreward.Table, feedbackreward.Columns, sqlgraph.NewFieldSpec(feedbackreward.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FeedbackReward.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedbackreward.FieldID)
		for _, f := range fields {
			if !feedbackreward.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feedbackreward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FeedbackID(); ok {
		_spec.SetField(feedbackreward.FieldFeedbackID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFeedbackID(); ok {
		_spec.AddField(feedbackreward.FieldFeedbackID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(feedbackreward.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(feedbackreward.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(feedbackreward.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(feedbackreward.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(feedbackreward.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(feedbackreward.FieldBatchID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperatorUserID(); ok {
		_spec.SetField(feedbackreward.FieldOperatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorUserID(); ok {
		_spec.AddField(feedbackreward.FieldOperatorUserID, field.TypeInt64, value)
	}
	if _u.mutation.OperatorUserIDCleared() {
		_spec.ClearField(feedbackreward.FieldOperatorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountChangeRecordID(); ok {
		_spec.SetField(feedbackreward.FieldAccountChangeRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountChangeRecordID(); ok {
		_spec.AddField(feedbackreward.FieldAccountChangeRecordID, field.TypeInt64, value)
	}
	if _u.mutation.AccountChangeRecordIDCleared() {
		_spec.ClearField(feedbackreward.FieldAccountChangeRecordID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(feedbackreward.FieldGrantedAt, field.TypeTime, value)
	}
	_node = &FeedbackReward{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedbackreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
