// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/feedbackreply"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// FeedbackReplyDelete is the builder for deleting a FeedbackReply entity.
type FeedbackReplyDelete struct {
	config
	hooks    []Hook
	mutation *FeedbackReplyMutation
}

// Where appends a list predicates to the FeedbackReplyDelete builder.
func (_d *FeedbackReplyDelete) Where(ps ...predicate.FeedbackReply) *FeedbackReplyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FeedbackReplyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FeedbackReplyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FeedbackReplyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(feedbackreply.Table, sqlgraph.NewFieldSpec(feedbackreply.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FeedbackReplyDeleteOne is the builder for deleting a single FeedbackReply entity.
type FeedbackReplyDeleteOne struct {
	_d *FeedbackReplyDelete
}

// Where appends a list predicates to the FeedbackReplyDelete builder.
func (_d *FeedbackReplyDeleteOne) Where(ps ...predicate.FeedbackReply) *FeedbackReplyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FeedbackReplyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{feedbackreply.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FeedbackReplyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
