// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/invoiceprofile"
	"github.com/bozhouDev/DragonCode-sub2api/ent/invoicerequest"
	"github.com/bozhouDev/DragonCode-sub2api/ent/invoicerequestorder"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
	"github.com/bozhouDev/DragonCode-sub2api/internal/domain"
)

// InvoiceRequestCreate is the builder for creating a InvoiceRequest entity.
type InvoiceRequestCreate struct {
	config
	mutation *InvoiceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceRequestCreate) SetCreatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceRequestCreate) SetUpdatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSerialNo sets the "serial_no" field.
func (_c *InvoiceRequestCreate) SetSerialNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetSerialNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceRequestCreate) SetUserID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *InvoiceRequestCreate) SetProfileID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableProfileID(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetProfileID(*v)
	}
	return _c
}

// SetProfileSnapshotJSON sets the "profile_snapshot_json" field.
func (_c *InvoiceRequestCreate) SetProfileSnapshotJSON(v domain.InvoiceProfileSnapshot) *InvoiceRequestCreate {
	_c.mutation.SetProfileSnapshotJSON(v)
	return _c
}

// SetTotalAmountFen sets the "total_amount_fen" field.
func (_c *InvoiceRequestCreate) SetTotalAmountFen(v int64) *InvoiceRequestCreate {
	_c.mutation.SetTotalAmountFen(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceRequestCreate) SetStatus(v string) *InvoiceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableStatus(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExportBatchNo sets the "export_batch_no" field.
func (_c *InvoiceRequestCreate) SetExportBatchNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetExportBatchNo(v)
	return _c
}

// SetNillableExportBatchNo sets the "export_batch_no" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableExportBatchNo(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetExportBatchNo(*v)
	}
	return _c
}

// SetExportedAt sets the "exported_at" field.
func (_c *InvoiceRequestCreate) SetExportedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetExportedAt(v)
	return _c
}

// SetNillableExportedAt sets the "exported_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableExportedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetExportedAt(*v)
	}
	return _c
}

// SetExportedBy sets the "exported_by" field.
func (_c *InvoiceRequestCreate) SetExportedBy(v int64) *InvoiceRequestCreate {
	_c.mutation.SetExportedBy(v)
	return _c
}

// SetNillableExportedBy sets the "exported_by" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableExportedBy(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetExportedBy(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *InvoiceRequestCreate) SetRemark(v string) *InvoiceRequestCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRemark(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetRejectReason sets the "reject_reason" field.
func (_c *InvoiceRequestCreate) SetRejectReason(v string) *InvoiceRequestCreate {
	_c.mutation.SetRejectReason(v)
	return _c
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRejectReason(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRejectReason(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *InvoiceRequestCreate) SetCompletedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCompletedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCompletedBy sets the "completed_by" field.
func (_c *InvoiceRequestCreate) SetCompletedBy(v int64) *InvoiceRequestCreate {
	_c.mutation.SetCompletedBy(v)
	return _c
}

// SetNillableCompletedBy sets the "completed_by" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCompletedBy(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCompletedBy(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceRequestCreate) SetUser(v *User) *InvoiceRequestCreate {
	return _c.SetUserID(v.ID)
}

// SetProfile sets the "profile" edge to the InvoiceProfile entity.
func (_c *InvoiceRequestCreate) SetProfile(v *InvoiceProfile) *InvoiceRequestCreate {
	return _c.SetProfileID(v.ID)
}

// AddRequestOrderIDs adds the "request_orders" edge to the InvoiceRequestOrder entity by IDs.
func (_c *InvoiceRequestCreate) AddRequestOrderIDs(ids ...int64) *InvoiceRequestCreate {
	_c.mutation.AddRequestOrderIDs(ids...)
	return _c
}

// AddRequestOrders adds the "request_orders" edges to the InvoiceRequestOrder entity.
func (_c *InvoiceRequestCreate) AddRequestOrders(v ...*InvoiceRequestOrder) *InvoiceRequestCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequestOrderIDs(ids...)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_c *InvoiceRequestCreate) Mutation() *InvoiceRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceRequest in the database.
func (_c *InvoiceRequestCreate) Save(ctx context.Context) (*InvoiceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestCreate) SaveX(ctx context.Context) *InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicerequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.SerialNo(); !ok {
		return &ValidationError{Name: "serial_no", err: errors.New(`ent: missing required field "InvoiceRequest.serial_no"`)}
	}
	if v, ok := _c.mutation.SerialNo(); ok {
		if err := invoicerequest.SerialNoValidator(v); err != nil {
			return &ValidationError{Name: "serial_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.serial_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceRequest.user_id"`)}
	}
	if _, ok := _c.mutation.ProfileSnapshotJSON(); !ok {
		return &ValidationError{Name: "profile_snapshot_json", err: errors.New(`ent: missing required field "InvoiceRequest.profile_snapshot_json"`)}
	}
	if _, ok := _c.mutation.TotalAmountFen(); !ok {
		return &ValidationError{Name: "total_amount_fen", err: errors.New(`ent: missing required field "InvoiceRequest.total_amount_fen"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExportBatchNo(); ok {
		if err := invoicerequest.ExportBatchNoValidator(v); err != nil {
			return &ValidationError{Name: "export_batch_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.export_batch_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RejectReason(); ok {
		if err := invoicerequest.RejectReasonValidator(v); err != nil {
			return &ValidationError{Name: "reject_reason", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.reject_reason": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceRequest.user"`)}
	}
	return nil
}

func (_c *InvoiceRequestCreate) sqlSave(ctx context.Context) (*InvoiceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestCreate) createSpec() (*InvoiceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequest.Table, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SerialNo(); ok {
		_spec.SetField(invoicerequest.FieldSerialNo, field.TypeString, value)
		_node.SerialNo = value
	}
	if value, ok := _c.mutation.ProfileSnapshotJSON(); ok {
		_spec.SetField(invoicerequest.FieldProfileSnapshotJSON, field.TypeJSON, value)
		_node.ProfileSnapshotJSON = value
	}
	if value, ok := _c.mutation.TotalAmountFen(); ok {
		_spec.SetField(invoicerequest.FieldTotalAmountFen, field.TypeInt64, value)
		_node.TotalAmountFen = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExportBatchNo(); ok {
		_spec.SetField(invoicerequest.FieldExportBatchNo, field.TypeString, value)
		_node.ExportBatchNo = &value
	}
	if value, ok := _c.mutation.ExportedAt(); ok {
		_spec.SetField(invoicerequest.FieldExportedAt, field.TypeTime, value)
		_node.ExportedAt = &value
	}
	if value, ok := _c.mutation.ExportedBy(); ok {
		_spec.SetField(invoicerequest.FieldExportedBy, field.TypeInt64, value)
		_node.ExportedBy = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(invoicerequest.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
		_node.RejectReason = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(invoicerequest.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CompletedBy(); ok {
		_spec.SetField(invoicerequest.FieldCompletedBy, field.TypeInt64, value)
		_node.CompletedBy = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.ProfileTable,
			Columns: []string{invoicerequest.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoiceprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProfileID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RequestOrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   invoicerequest.RequestOrdersTable,
			Columns: []string{invoicerequest.RequestOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoicerequestorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflictColumns(columns ...string) *InvoiceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequest node.
	InvoiceRequestUpsertOne struct {
		create *InvoiceRequestCreate
	}

	// InvoiceRequestUpsert is the "OnConflict" setter.
	InvoiceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsert) SetUpdatedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUpdatedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUpdatedAt)
	return u
}

// SetSerialNo sets the "serial_no" field.
func (u *InvoiceRequestUpsert) SetSerialNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldSerialNo, v)
	return u
}

// UpdateSerialNo sets the "serial_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateSerialNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldSerialNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsert) SetUserID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserID)
	return u
}

// SetProfileID sets the "profile_id" field.
func (u *InvoiceRequestUpsert) SetProfileID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldProfileID, v)
	return u
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateProfileID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldProfileID)
	return u
}

// ClearProfileID clears the value of the "profile_id" field.
func (u *InvoiceRequestUpsert) ClearProfileID() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldProfileID)
	return u
}

// SetProfileSnapshotJSON sets the "profile_snapshot_json" field.
func (u *InvoiceRequestUpsert) SetProfileSnapshotJSON(v domain.InvoiceProfileSnapshot) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldProfileSnapshotJSON, v)
	return u
}

// UpdateProfileSnapshotJSON sets the "profile_snapshot_json" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateProfileSnapshotJSON() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldProfileSnapshotJSON)
	return u
}

// SetTotalAmountFen sets the "total_amount_fen" field.
func (u *InvoiceRequestUpsert) SetTotalAmountFen(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTotalAmountFen, v)
	return u
}

// UpdateTotalAmountFen sets the "total_amount_fen" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTotalAmountFen() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTotalAmountFen)
	return u
}

// AddTotalAmountFen adds v to the "total_amount_fen" field.
func (u *InvoiceRequestUpsert) AddTotalAmountFen(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldTotalAmountFen, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsert) SetStatus(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateStatus() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldStatus)
	return u
}

// SetExportBatchNo sets the "export_batch_no" field.
func (u *InvoiceRequestUpsert) SetExportBatchNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldExportBatchNo, v)
	return u
}

// UpdateExportBatchNo sets the "export_batch_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateExportBatchNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldExportBatchNo)
	return u
}

// ClearExportBatchNo clears the value of the "export_batch_no" field.
func (u *InvoiceRequestUpsert) ClearExportBatchNo() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldExportBatchNo)
	return u
}

// SetExportedAt sets the "exported_at" field.
func (u *InvoiceRequestUpsert) SetExportedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldExportedAt, v)
	return u
}

// UpdateExportedAt sets the "exported_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateExportedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldExportedAt)
	return u
}

// ClearExportedAt clears the value of the "exported_at" field.
func (u *InvoiceRequestUpsert) ClearExportedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldExportedAt)
	return u
}

// SetExportedBy sets the "exported_by" field.
func (u *InvoiceRequestUpsert) SetExportedBy(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldExportedBy, v)
	return u
}

// UpdateExportedBy sets the "exported_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateExportedBy() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldExportedBy)
	return u
}

// AddExportedBy adds v to the "exported_by" field.
func (u *InvoiceRequestUpsert) AddExportedBy(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldExportedBy, v)
	return u
}

// ClearExportedBy clears the value of the "exported_by" field.
func (u *InvoiceRequestUpsert) ClearExportedBy() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldExportedBy)
	return u
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsert) SetRemark(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRemark() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsert) ClearRemark() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRemark)
	return u
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsert) SetRejectReason(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRejectReason, v)
	return u
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRejectReason() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRejectReason)
	return u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsert) ClearRejectReason() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRejectReason)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *InvoiceRequestUpsert) SetCompletedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateCompletedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InvoiceRequestUpsert) ClearCompletedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldCompletedAt)
	return u
}

// SetCompletedBy sets the "completed_by" field.
func (u *InvoiceRequestUpsert) SetCompletedBy(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldCompletedBy, v)
	return u
}

// UpdateCompletedBy sets the "completed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateCompletedBy() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldCompletedBy)
	return u
}

// AddCompletedBy adds v to the "completed_by" field.
func (u *InvoiceRequestUpsert) AddCompletedBy(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldCompletedBy, v)
	return u
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (u *InvoiceRequestUpsert) ClearCompletedBy() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldCompletedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertOne) UpdateNewValues() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestUpsertOne) Ignore() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertOne) DoNothing() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertOne) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUpdatedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSerialNo sets the "serial_no" field.
func (u *InvoiceRequestUpsertOne) SetSerialNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSerialNo(v)
	})
}

// UpdateSerialNo sets the "serial_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateSerialNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSerialNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertOne) SetUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetProfileID sets the "profile_id" field.
func (u *InvoiceRequestUpsertOne) SetProfileID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateProfileID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProfileID()
	})
}

// ClearProfileID clears the value of the "profile_id" field.
func (u *InvoiceRequestUpsertOne) ClearProfileID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearProfileID()
	})
}

// SetProfileSnapshotJSON sets the "profile_snapshot_json" field.
func (u *InvoiceRequestUpsertOne) SetProfileSnapshotJSON(v domain.InvoiceProfileSnapshot) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProfileSnapshotJSON(v)
	})
}

// UpdateProfileSnapshotJSON sets the "profile_snapshot_json" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateProfileSnapshotJSON() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProfileSnapshotJSON()
	})
}

// SetTotalAmountFen sets the "total_amount_fen" field.
func (u *InvoiceRequestUpsertOne) SetTotalAmountFen(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTotalAmountFen(v)
	})
}

// AddTotalAmountFen adds v to the "total_amount_fen" field.
func (u *InvoiceRequestUpsertOne) AddTotalAmountFen(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTotalAmountFen(v)
	})
}

// UpdateTotalAmountFen sets the "total_amount_fen" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTotalAmountFen() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTotalAmountFen()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertOne) SetStatus(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateStatus() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetExportBatchNo sets the "export_batch_no" field.
func (u *InvoiceRequestUpsertOne) SetExportBatchNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExportBatchNo(v)
	})
}

// UpdateExportBatchNo sets the "export_batch_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateExportBatchNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExportBatchNo()
	})
}

// ClearExportBatchNo clears the value of the "export_batch_no" field.
func (u *InvoiceRequestUpsertOne) ClearExportBatchNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearExportBatchNo()
	})
}

// SetExportedAt sets the "exported_at" field.
func (u *InvoiceRequestUpsertOne) SetExportedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExportedAt(v)
	})
}

// UpdateExportedAt sets the "exported_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateExportedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExportedAt()
	})
}

// ClearExportedAt clears the value of the "exported_at" field.
func (u *InvoiceRequestUpsertOne) ClearExportedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearExportedAt()
	})
}

// SetExportedBy sets the "exported_by" field.
func (u *InvoiceRequestUpsertOne) SetExportedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExportedBy(v)
	})
}

// AddExportedBy adds v to the "exported_by" field.
func (u *InvoiceRequestUpsertOne) AddExportedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddExportedBy(v)
	})
}

// UpdateExportedBy sets the "exported_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateExportedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExportedBy()
	})
}

// ClearExportedBy clears the value of the "exported_by" field.
func (u *InvoiceRequestUpsertOne) ClearExportedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearExportedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertOne) SetRemark(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsertOne) ClearRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRemark()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsertOne) SetRejectReason(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRejectReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsertOne) ClearRejectReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectReason()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *InvoiceRequestUpsertOne) SetCompletedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateCompletedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InvoiceRequestUpsertOne) ClearCompletedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearCompletedAt()
	})
}

// SetCompletedBy sets the "completed_by" field.
func (u *InvoiceRequestUpsertOne) SetCompletedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCompletedBy(v)
	})
}

// AddCompletedBy adds v to the "completed_by" field.
func (u *InvoiceRequestUpsertOne) AddCompletedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddCompletedBy(v)
	})
}

// UpdateCompletedBy sets the "completed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateCompletedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCompletedBy()
	})
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (u *InvoiceRequestUpsertOne) ClearCompletedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearCompletedBy()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestCreateBulk is the builder for creating many InvoiceRequest entities in bulk.
type InvoiceRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequest entities in the database.
func (_c *InvoiceRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequest nodes.
type InvoiceRequestUpsertBulk struct {
	create *InvoiceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) UpdateNewValues() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) Ignore() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertBulk) DoNothing() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertBulk) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUpdatedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSerialNo sets the "serial_no" field.
func (u *InvoiceRequestUpsertBulk) SetSerialNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSerialNo(v)
	})
}

// UpdateSerialNo sets the "serial_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateSerialNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSerialNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertBulk) SetUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetProfileID sets the "profile_id" field.
func (u *InvoiceRequestUpsertBulk) SetProfileID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateProfileID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProfileID()
	})
}

// ClearProfileID clears the value of the "profile_id" field.
func (u *InvoiceRequestUpsertBulk) ClearProfileID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearProfileID()
	})
}

// SetProfileSnapshotJSON sets the "profile_snapshot_json" field.
func (u *InvoiceRequestUpsertBulk) SetProfileSnapshotJSON(v domain.InvoiceProfileSnapshot) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProfileSnapshotJSON(v)
	})
}

// UpdateProfileSnapshotJSON sets the "profile_snapshot_json" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateProfileSnapshotJSON() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProfileSnapshotJSON()
	})
}

// SetTotalAmountFen sets the "total_amount_fen" field.
func (u *InvoiceRequestUpsertBulk) SetTotalAmountFen(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTotalAmountFen(v)
	})
}

// AddTotalAmountFen adds v to the "total_amount_fen" field.
func (u *InvoiceRequestUpsertBulk) AddTotalAmountFen(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddTotalAmountFen(v)
	})
}

// UpdateTotalAmountFen sets the "total_amount_fen" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTotalAmountFen() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTotalAmountFen()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertBulk) SetStatus(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateStatus() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetExportBatchNo sets the "export_batch_no" field.
func (u *InvoiceRequestUpsertBulk) SetExportBatchNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExportBatchNo(v)
	})
}

// UpdateExportBatchNo sets the "export_batch_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateExportBatchNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExportBatchNo()
	})
}

// ClearExportBatchNo clears the value of the "export_batch_no" field.
func (u *InvoiceRequestUpsertBulk) ClearExportBatchNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearExportBatchNo()
	})
}

// SetExportedAt sets the "exported_at" field.
func (u *InvoiceRequestUpsertBulk) SetExportedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExportedAt(v)
	})
}

// UpdateExportedAt sets the "exported_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateExportedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExportedAt()
	})
}

// ClearExportedAt clears the value of the "exported_at" field.
func (u *InvoiceRequestUpsertBulk) ClearExportedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearExportedAt()
	})
}

// SetExportedBy sets the "exported_by" field.
func (u *InvoiceRequestUpsertBulk) SetExportedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetExportedBy(v)
	})
}

// AddExportedBy adds v to the "exported_by" field.
func (u *InvoiceRequestUpsertBulk) AddExportedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddExportedBy(v)
	})
}

// UpdateExportedBy sets the "exported_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateExportedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateExportedBy()
	})
}

// ClearExportedBy clears the value of the "exported_by" field.
func (u *InvoiceRequestUpsertBulk) ClearExportedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearExportedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertBulk) SetRemark(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *InvoiceRequestUpsertBulk) ClearRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRemark()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsertBulk) SetRejectReason(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRejectReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsertBulk) ClearRejectReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectReason()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *InvoiceRequestUpsertBulk) SetCompletedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateCompletedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *InvoiceRequestUpsertBulk) ClearCompletedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearCompletedAt()
	})
}

// SetCompletedBy sets the "completed_by" field.
func (u *InvoiceRequestUpsertBulk) SetCompletedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCompletedBy(v)
	})
}

// AddCompletedBy adds v to the "completed_by" field.
func (u *InvoiceRequestUpsertBulk) AddCompletedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddCompletedBy(v)
	})
}

// UpdateCompletedBy sets the "completed_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateCompletedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCompletedBy()
	})
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (u *InvoiceRequestUpsertBulk) ClearCompletedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearCompletedBy()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
