// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/invoicerequest"
	"github.com/bozhouDev/DragonCode-sub2api/ent/invoicerequestorder"
	"github.com/bozhouDev/DragonCode-sub2api/ent/topuporder"
)

// InvoiceRequestOrder is the model entity for the InvoiceRequestOrder schema.
type InvoiceRequestOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// InvoiceRequestID holds the value of the "invoice_request_id" field.
	InvoiceRequestID int64 `json:"invoice_request_id,omitempty"`
	// TopupOrderID holds the value of the "topup_order_id" field.
	TopupOrderID int64 `json:"topup_order_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceRequestOrderQuery when eager-loading is set.
	Edges        InvoiceRequestOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceRequestOrderEdges holds the relations/edges for other nodes in the graph.
type InvoiceRequestOrderEdges struct {
	// InvoiceRequest holds the value of the invoice_request edge.
	InvoiceRequest *InvoiceRequest `json:"invoice_request,omitempty"`
	// TopupOrder holds the value of the topup_order edge.
	TopupOrder *TopupOrder `json:"topup_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// InvoiceRequestOrErr returns the InvoiceRequest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceRequestOrderEdges) InvoiceRequestOrErr() (*InvoiceRequest, error) {
	if e.InvoiceRequest != nil {
		return e.InvoiceRequest, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invoicerequest.Label}
	}
	return nil, &NotLoadedError{edge: "invoice_request"}
}

// TopupOrderOrErr returns the TopupOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceRequestOrderEdges) TopupOrderOrErr() (*TopupOrder, error) {
	if e.TopupOrder != nil {
		return e.TopupOrder, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: topuporder.Label}
	}
	return nil, &NotLoadedError{edge: "topup_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceRequestOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicerequestorder.FieldID, invoicerequestorder.FieldInvoiceRequestID, invoicerequestorder.FieldTopupOrderID:
			values[i] = new(sql.NullInt64)
		case invoicerequestorder.FieldCreatedAt, invoicerequestorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceRequestOrder fields.
func (_m *InvoiceRequestOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicerequestorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicerequestorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoicerequestorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case invoicerequestorder.FieldInvoiceRequestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_request_id", values[i])
			} else if value.Valid {
				_m.InvoiceRequestID = value.Int64
			}
		case invoicerequestorder.FieldTopupOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field topup_order_id", values[i])
			} else if value.Valid {
				_m.TopupOrderID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceRequestOrder.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceRequestOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvoiceRequest queries the "invoice_request" edge of the InvoiceRequestOrder entity.
func (_m *InvoiceRequestOrder) QueryInvoiceRequest() *InvoiceRequestQuery {
	return NewInvoiceRequestOrderClient(_m.config).QueryInvoiceRequest(_m)
}

// QueryTopupOrder queries the "topup_order" edge of the InvoiceRequestOrder entity.
func (_m *InvoiceRequestOrder) QueryTopupOrder() *TopupOrderQuery {
	return NewInvoiceRequestOrderClient(_m.config).QueryTopupOrder(_m)
}

// Update returns a builder for updating this InvoiceRequestOrder.
// Note that you need to call InvoiceRequestOrder.Unwrap() before calling this method if this InvoiceRequestOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceRequestOrder) Update() *InvoiceRequestOrderUpdateOne {
	return NewInvoiceRequestOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceRequestOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceRequestOrder) Unwrap() *InvoiceRequestOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceRequestOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceRequestOrder) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceRequestOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("invoice_request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InvoiceRequestID))
	builder.WriteString(", ")
	builder.WriteString("topup_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TopupOrderID))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceRequestOrders is a parsable slice of InvoiceRequestOrder.
type InvoiceRequestOrders []*InvoiceRequestOrder
