// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozhouDev/DragonCode-sub2api/ent/paymentorder"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdate) SetOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PaymentOrderUpdate) SetAmountCents(v int) *PaymentOrderUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmountCents(v *int) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PaymentOrderUpdate) AddAmountCents(v int) *PaymentOrderUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PaymentOrderUpdate) SetPlanID(v string) *PaymentOrderUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePlanID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PaymentOrderUpdate) SetGroupID(v int64) *PaymentOrderUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableGroupID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *PaymentOrderUpdate) AddGroupID(v int64) *PaymentOrderUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *PaymentOrderUpdate) SetValidityDays(v int) *PaymentOrderUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableValidityDays(v *int) *PaymentOrderUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *PaymentOrderUpdate) AddValidityDays(v int) *PaymentOrderUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_u *PaymentOrderUpdate) SetAlipayTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetAlipayTradeNo(v)
	return _u
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAlipayTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAlipayTradeNo(*v)
	}
	return _u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (_u *PaymentOrderUpdate) ClearAlipayTradeNo() *PaymentOrderUpdate {
	_u.mutation.ClearAlipayTradeNo()
	return _u
}

// SetQrCodeURL sets the "qr_code_url" field.
func (_u *PaymentOrderUpdate) SetQrCodeURL(v string) *PaymentOrderUpdate {
	_u.mutation.SetQrCodeURL(v)
	return _u
}

// SetNillableQrCodeURL sets the "qr_code_url" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableQrCodeURL(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetQrCodeURL(*v)
	}
	return _u
}

// ClearQrCodeURL clears the value of the "qr_code_url" field.
func (_u *PaymentOrderUpdate) ClearQrCodeURL() *PaymentOrderUpdate {
	_u.mutation.ClearQrCodeURL()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PaymentOrderUpdate) SetCompletedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCompletedAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PaymentOrderUpdate) ClearCompletedAt() *PaymentOrderUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanID(); ok {
		if err := paymentorder.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.plan_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTradeNo(); ok {
		if err := paymentorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trade_no": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(paymentorder.FieldPlanID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(paymentorder.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(paymentorder.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(paymentorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(paymentorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlipayTradeNo(); ok {
		_spec.SetField(paymentorder.FieldAlipayTradeNo, field.TypeString, value)
	}
	if _u.mutation.AlipayTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldAlipayTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.QrCodeURL(); ok {
		_spec.SetField(paymentorder.FieldQrCodeURL, field.TypeString, value)
	}
	if _u.mutation.QrCodeURLCleared() {
		_spec.ClearField(paymentorder.FieldQrCodeURL, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(paymentorder.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(paymentorder.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdateOne) SetOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PaymentOrderUpdateOne) SetAmountCents(v int) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmountCents(v *int) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PaymentOrderUpdateOne) AddAmountCents(v int) *PaymentOrderUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PaymentOrderUpdateOne) SetPlanID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePlanID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PaymentOrderUpdateOne) SetGroupID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableGroupID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *PaymentOrderUpdateOne) AddGroupID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *PaymentOrderUpdateOne) SetValidityDays(v int) *PaymentOrderUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableValidityDays(v *int) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *PaymentOrderUpdateOne) AddValidityDays(v int) *PaymentOrderUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_u *PaymentOrderUpdateOne) SetAlipayTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetAlipayTradeNo(v)
	return _u
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAlipayTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAlipayTradeNo(*v)
	}
	return _u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (_u *PaymentOrderUpdateOne) ClearAlipayTradeNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearAlipayTradeNo()
	return _u
}

// SetQrCodeURL sets the "qr_code_url" field.
func (_u *PaymentOrderUpdateOne) SetQrCodeURL(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetQrCodeURL(v)
	return _u
}

// SetNillableQrCodeURL sets the "qr_code_url" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableQrCodeURL(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetQrCodeURL(*v)
	}
	return _u
}

// ClearQrCodeURL clears the value of the "qr_code_url" field.
func (_u *PaymentOrderUpdateOne) ClearQrCodeURL() *PaymentOrderUpdateOne {
	_u.mutation.ClearQrCodeURL()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PaymentOrderUpdateOne) SetCompletedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCompletedAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PaymentOrderUpdateOne) ClearCompletedAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanID(); ok {
		if err := paymentorder.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.plan_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTradeNo(); ok {
		if err := paymentorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trade_no": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(paymentorder.FieldPlanID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(paymentorder.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(paymentorder.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(paymentorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(paymentorder.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlipayTradeNo(); ok {
		_spec.SetField(paymentorder.FieldAlipayTradeNo, field.TypeString, value)
	}
	if _u.mutation.AlipayTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldAlipayTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.QrCodeURL(); ok {
		_spec.SetField(paymentorder.FieldQrCodeURL, field.TypeString, value)
	}
	if _u.mutation.QrCodeURLCleared() {
		_spec.ClearField(paymentorder.FieldQrCodeURL, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(paymentorder.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(paymentorder.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
