// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/topuporder"
	"github.com/bozhouDev/DragonCode-sub2api/ent/user"
)

// TopupOrder is the model entity for the TopupOrder schema.
type TopupOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AmountCnyFen holds the value of the "amount_cny_fen" field.
	AmountCnyFen int `json:"amount_cny_fen,omitempty"`
	// BonusAmountCnyFen holds the value of the "bonus_amount_cny_fen" field.
	BonusAmountCnyFen int `json:"bonus_amount_cny_fen,omitempty"`
	// PayType holds the value of the "pay_type" field.
	PayType string `json:"pay_type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// InvoiceStatus holds the value of the "invoice_status" field.
	InvoiceStatus string `json:"invoice_status,omitempty"`
	// XunhuTradeNo holds the value of the "xunhu_trade_no" field.
	XunhuTradeNo *string `json:"xunhu_trade_no,omitempty"`
	// QrCodeURL holds the value of the "qr_code_url" field.
	QrCodeURL *string `json:"qr_code_url,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TopupOrderQuery when eager-loading is set.
	Edges        TopupOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TopupOrderEdges holds the relations/edges for other nodes in the graph.
type TopupOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// InvoiceRequestOrders holds the value of the invoice_request_orders edge.
	InvoiceRequestOrders []*InvoiceRequestOrder `json:"invoice_request_orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TopupOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// InvoiceRequestOrdersOrErr returns the InvoiceRequestOrders value or an error if the edge
// was not loaded in eager-loading.
func (e TopupOrderEdges) InvoiceRequestOrdersOrErr() ([]*InvoiceRequestOrder, error) {
	if e.loadedTypes[1] {
		return e.InvoiceRequestOrders, nil
	}
	return nil, &NotLoadedError{edge: "invoice_request_orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TopupOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case topuporder.FieldID, topuporder.FieldUserID, topuporder.FieldAmountCnyFen, topuporder.FieldBonusAmountCnyFen:
			values[i] = new(sql.NullInt64)
		case topuporder.FieldOrderNo, topuporder.FieldPayType, topuporder.FieldStatus, topuporder.FieldInvoiceStatus, topuporder.FieldXunhuTradeNo, topuporder.FieldQrCodeURL:
			values[i] = new(sql.NullString)
		case topuporder.FieldCompletedAt, topuporder.FieldCreatedAt, topuporder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TopupOrder fields.
func (_m *TopupOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case topuporder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case topuporder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case topuporder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case topuporder.FieldAmountCnyFen:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cny_fen", values[i])
			} else if value.Valid {
				_m.AmountCnyFen = int(value.Int64)
			}
		case topuporder.FieldBonusAmountCnyFen:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_amount_cny_fen", values[i])
			} else if value.Valid {
				_m.BonusAmountCnyFen = int(value.Int64)
			}
		case topuporder.FieldPayType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pay_type", values[i])
			} else if value.Valid {
				_m.PayType = value.String
			}
		case topuporder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case topuporder.FieldInvoiceStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_status", values[i])
			} else if value.Valid {
				_m.InvoiceStatus = value.String
			}
		case topuporder.FieldXunhuTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field xunhu_trade_no", values[i])
			} else if value.Valid {
				_m.XunhuTradeNo = new(string)
				*_m.XunhuTradeNo = value.String
			}
		case topuporder.FieldQrCodeURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_code_url", values[i])
			} else if value.Valid {
				_m.QrCodeURL = new(string)
				*_m.QrCodeURL = value.String
			}
		case topuporder.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case topuporder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case topuporder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TopupOrder.
// This includes values selected through modifiers, order, etc.
func (_m *TopupOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TopupOrder entity.
func (_m *TopupOrder) QueryUser() *UserQuery {
	return NewTopupOrderClient(_m.config).QueryUser(_m)
}

// QueryInvoiceRequestOrders queries the "invoice_request_orders" edge of the TopupOrder entity.
func (_m *TopupOrder) QueryInvoiceRequestOrders() *InvoiceRequestOrderQuery {
	return NewTopupOrderClient(_m.config).QueryInvoiceRequestOrders(_m)
}

// Update returns a builder for updating this TopupOrder.
// Note that you need to call TopupOrder.Unwrap() before calling this method if this TopupOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TopupOrder) Update() *TopupOrderUpdateOne {
	return NewTopupOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TopupOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TopupOrder) Unwrap() *TopupOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TopupOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TopupOrder) String() string {
	var builder strings.Builder
	builder.WriteString("TopupOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount_cny_fen=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCnyFen))
	builder.WriteString(", ")
	builder.WriteString("bonus_amount_cny_fen=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusAmountCnyFen))
	builder.WriteString(", ")
	builder.WriteString("pay_type=")
	builder.WriteString(_m.PayType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("invoice_status=")
	builder.WriteString(_m.InvoiceStatus)
	builder.WriteString(", ")
	if v := _m.XunhuTradeNo; v != nil {
		builder.WriteString("xunhu_trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.QrCodeURL; v != nil {
		builder.WriteString("qr_code_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TopupOrders is a parsable slice of TopupOrder.
type TopupOrders []*TopupOrder
