// Code generated by ent, DO NOT EDIT.

package accountchangerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldUserID, v))
}

// AssetType applies equality check predicate on the "asset_type" field. It's identical to AssetTypeEQ.
func AssetType(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldAssetType, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldReason, v))
}

// Delta applies equality check predicate on the "delta" field. It's identical to DeltaEQ.
func Delta(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldDelta, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldSourceID, v))
}

// ReferenceNo applies equality check predicate on the "reference_no" field. It's identical to ReferenceNoEQ.
func ReferenceNo(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldReferenceNo, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldOperatorUserID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldNotes, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldGroupID, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldValidityDays, v))
}

// DedupeKey applies equality check predicate on the "dedupe_key" field. It's identical to DedupeKeyEQ.
func DedupeKey(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldDedupeKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// AssetTypeEQ applies the EQ predicate on the "asset_type" field.
func AssetTypeEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldAssetType, v))
}

// AssetTypeNEQ applies the NEQ predicate on the "asset_type" field.
func AssetTypeNEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldAssetType, v))
}

// AssetTypeIn applies the In predicate on the "asset_type" field.
func AssetTypeIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldAssetType, vs...))
}

// AssetTypeNotIn applies the NotIn predicate on the "asset_type" field.
func AssetTypeNotIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldAssetType, vs...))
}

// AssetTypeGT applies the GT predicate on the "asset_type" field.
func AssetTypeGT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldAssetType, v))
}

// AssetTypeGTE applies the GTE predicate on the "asset_type" field.
func AssetTypeGTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldAssetType, v))
}

// AssetTypeLT applies the LT predicate on the "asset_type" field.
func AssetTypeLT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldAssetType, v))
}

// AssetTypeLTE applies the LTE predicate on the "asset_type" field.
func AssetTypeLTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldAssetType, v))
}

// AssetTypeContains applies the Contains predicate on the "asset_type" field.
func AssetTypeContains(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContains(FieldAssetType, v))
}

// AssetTypeHasPrefix applies the HasPrefix predicate on the "asset_type" field.
func AssetTypeHasPrefix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasPrefix(FieldAssetType, v))
}

// AssetTypeHasSuffix applies the HasSuffix predicate on the "asset_type" field.
func AssetTypeHasSuffix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasSuffix(FieldAssetType, v))
}

// AssetTypeEqualFold applies the EqualFold predicate on the "asset_type" field.
func AssetTypeEqualFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEqualFold(FieldAssetType, v))
}

// AssetTypeContainsFold applies the ContainsFold predicate on the "asset_type" field.
func AssetTypeContainsFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContainsFold(FieldAssetType, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContainsFold(FieldReason, v))
}

// DeltaEQ applies the EQ predicate on the "delta" field.
func DeltaEQ(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldDelta, v))
}

// DeltaNEQ applies the NEQ predicate on the "delta" field.
func DeltaNEQ(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldDelta, v))
}

// DeltaIn applies the In predicate on the "delta" field.
func DeltaIn(vs ...float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldDelta, vs...))
}

// DeltaNotIn applies the NotIn predicate on the "delta" field.
func DeltaNotIn(vs ...float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldDelta, vs...))
}

// DeltaGT applies the GT predicate on the "delta" field.
func DeltaGT(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldDelta, v))
}

// DeltaGTE applies the GTE predicate on the "delta" field.
func DeltaGTE(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldDelta, v))
}

// DeltaLT applies the LT predicate on the "delta" field.
func DeltaLT(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldDelta, v))
}

// DeltaLTE applies the LTE predicate on the "delta" field.
func DeltaLTE(v float64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldDelta, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotNull(FieldSourceID))
}

// ReferenceNoEQ applies the EQ predicate on the "reference_no" field.
func ReferenceNoEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldReferenceNo, v))
}

// ReferenceNoNEQ applies the NEQ predicate on the "reference_no" field.
func ReferenceNoNEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldReferenceNo, v))
}

// ReferenceNoIn applies the In predicate on the "reference_no" field.
func ReferenceNoIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldReferenceNo, vs...))
}

// ReferenceNoNotIn applies the NotIn predicate on the "reference_no" field.
func ReferenceNoNotIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldReferenceNo, vs...))
}

// ReferenceNoGT applies the GT predicate on the "reference_no" field.
func ReferenceNoGT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldReferenceNo, v))
}

// ReferenceNoGTE applies the GTE predicate on the "reference_no" field.
func ReferenceNoGTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldReferenceNo, v))
}

// ReferenceNoLT applies the LT predicate on the "reference_no" field.
func ReferenceNoLT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldReferenceNo, v))
}

// ReferenceNoLTE applies the LTE predicate on the "reference_no" field.
func ReferenceNoLTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldReferenceNo, v))
}

// ReferenceNoContains applies the Contains predicate on the "reference_no" field.
func ReferenceNoContains(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContains(FieldReferenceNo, v))
}

// ReferenceNoHasPrefix applies the HasPrefix predicate on the "reference_no" field.
func ReferenceNoHasPrefix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasPrefix(FieldReferenceNo, v))
}

// ReferenceNoHasSuffix applies the HasSuffix predicate on the "reference_no" field.
func ReferenceNoHasSuffix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasSuffix(FieldReferenceNo, v))
}

// ReferenceNoIsNil applies the IsNil predicate on the "reference_no" field.
func ReferenceNoIsNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIsNull(FieldReferenceNo))
}

// ReferenceNoNotNil applies the NotNil predicate on the "reference_no" field.
func ReferenceNoNotNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotNull(FieldReferenceNo))
}

// ReferenceNoEqualFold applies the EqualFold predicate on the "reference_no" field.
func ReferenceNoEqualFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEqualFold(FieldReferenceNo, v))
}

// ReferenceNoContainsFold applies the ContainsFold predicate on the "reference_no" field.
func ReferenceNoContainsFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContainsFold(FieldReferenceNo, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldOperatorUserID, v))
}

// OperatorUserIDIsNil applies the IsNil predicate on the "operator_user_id" field.
func OperatorUserIDIsNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIsNull(FieldOperatorUserID))
}

// OperatorUserIDNotNil applies the NotNil predicate on the "operator_user_id" field.
func OperatorUserIDNotNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotNull(FieldOperatorUserID))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContainsFold(FieldNotes, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotNull(FieldGroupID))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldValidityDays, v))
}

// DedupeKeyEQ applies the EQ predicate on the "dedupe_key" field.
func DedupeKeyEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldDedupeKey, v))
}

// DedupeKeyNEQ applies the NEQ predicate on the "dedupe_key" field.
func DedupeKeyNEQ(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldDedupeKey, v))
}

// DedupeKeyIn applies the In predicate on the "dedupe_key" field.
func DedupeKeyIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldDedupeKey, vs...))
}

// DedupeKeyNotIn applies the NotIn predicate on the "dedupe_key" field.
func DedupeKeyNotIn(vs ...string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldDedupeKey, vs...))
}

// DedupeKeyGT applies the GT predicate on the "dedupe_key" field.
func DedupeKeyGT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldDedupeKey, v))
}

// DedupeKeyGTE applies the GTE predicate on the "dedupe_key" field.
func DedupeKeyGTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldDedupeKey, v))
}

// DedupeKeyLT applies the LT predicate on the "dedupe_key" field.
func DedupeKeyLT(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldDedupeKey, v))
}

// DedupeKeyLTE applies the LTE predicate on the "dedupe_key" field.
func DedupeKeyLTE(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldDedupeKey, v))
}

// DedupeKeyContains applies the Contains predicate on the "dedupe_key" field.
func DedupeKeyContains(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContains(FieldDedupeKey, v))
}

// DedupeKeyHasPrefix applies the HasPrefix predicate on the "dedupe_key" field.
func DedupeKeyHasPrefix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasPrefix(FieldDedupeKey, v))
}

// DedupeKeyHasSuffix applies the HasSuffix predicate on the "dedupe_key" field.
func DedupeKeyHasSuffix(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldHasSuffix(FieldDedupeKey, v))
}

// DedupeKeyIsNil applies the IsNil predicate on the "dedupe_key" field.
func DedupeKeyIsNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIsNull(FieldDedupeKey))
}

// DedupeKeyNotNil applies the NotNil predicate on the "dedupe_key" field.
func DedupeKeyNotNil() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotNull(FieldDedupeKey))
}

// DedupeKeyEqualFold applies the EqualFold predicate on the "dedupe_key" field.
func DedupeKeyEqualFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEqualFold(FieldDedupeKey, v))
}

// DedupeKeyContainsFold applies the ContainsFold predicate on the "dedupe_key" field.
func DedupeKeyContainsFold(v string) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldContainsFold(FieldDedupeKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountChangeRecord) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountChangeRecord) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountChangeRecord) predicate.AccountChangeRecord {
	return predicate.AccountChangeRecord(sql.NotPredicates(p))
}
