import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
const api=vi.hoisted(()=>({getCompensationSnapshot:vi.fn(),getCompensationDraft:vi.fn(),updateCompensationShadow:vi.fn(),generateCompensationDraft:vi.fn(),reviseCompensationDraft:vi.fn(),reviewCompensationDraft:vi.fn(),getCompensationExecutionPreview:vi.fn(),approveCompensationDraft:vi.fn(),updateCompensationExecutionEnabled:vi.fn(),executeCompensationDraft:vi.fn(),refundErroneousCharge:vi.fn()}));vi.mock('@/api/admin/compensation',()=>api)
import CompensationShadowView from '../CompensationShadowView.vue'
const item={id:1,user_id:7,product_id:1,product_name:'OpenAI / Codex API',group_id:2,group_name:'OpenAI',benefit_channel:'balance',first_qualifying_failure_at:new Date().toISOString(),compensable_duration_ms:1800000,product_rate_cny_fen_per_hour:3000,group_weight_bps:10000,tier_multiplier_bps:12500,raw_value_cny_micros:18750000,proposed_cny_fen:600}
const user={id:1,user_id:7,email:'customer@example.com',tier:'priority',eligible:true,included:true,final_failure_count:4,verified_paid_value_cny_fen:30000,raw_value_cny_micros:93750000,tier_cap_cny_fen:5000,relationship_cap_cny_fen:3000,proposed_total_cny_fen:3000,balance_benefit_cny_fen:600,builder_pass_benefit_cny_fen:2400,limiting_cap:'relationship',items:[item,{...item,id:2,product_name:'Builder Pass GPT',benefit_channel:'builder_pass',proposed_cny_fen:2400}]}
const draft={id:10,series_id:'series',incident_id:5,policy_version:1,revision_number:1,state:'shadow',redesigned:false,eligible_user_count:1,affected_user_count:1,proposed_total_cny_fen:3000,affected_product_rolling_paid_value_cny_fen:60000,high_value_threshold_cny_fen:6000,high_value:false,evidence_hash:'a'.repeat(64),created_at:new Date().toISOString(),users:[user]}
const executionPreview={draft_id:10,latest:true,incident_resolved:true,shadow_gate_eligible:true,execution_enabled:true,approval_id:9,total_cny_fen:3000,balance_cny_fen:600,builder_pass_cny_fen:2400,user_count:1,executable:true,blockers:[],approval_preview_hash:'b'.repeat(64),notice_previews:[{user_id:7,services:['OpenAI / Codex API'],balance_cny_fen:600,builder_pass_cny_fen:2400,failed_requests_charged:false,body:'受影响服务：OpenAI / Codex API。影响时段：2026-08-24 10:00 北京时间 至 2026-08-24 10:30 北京时间。已发放：余额 ¥6.00、Builder Pass ¥24.00。未发现最终失败请求扣费。'}]}
const snapshot={enabled:true,generated_at:new Date().toISOString(),assessment:{enabled:true,started_at:new Date().toISOString(),elapsed_days:2,evaluated_incident_count:1,reviewed_incident_count:0,evidence_complete:true,minimum_days:30,minimum_incidents:3,eligible_for_owner_review:false,execution_available:false},drafts:[{...draft,users:undefined}]}
const mountView=()=>mount(CompensationShadowView,{global:{stubs:{AppLayout:{template:'<div><slot /></div>'}}}})
beforeEach(()=>{vi.clearAllMocks();api.getCompensationSnapshot.mockResolvedValue(structuredClone(snapshot));api.getCompensationDraft.mockResolvedValue(structuredClone(draft));api.updateCompensationShadow.mockResolvedValue(undefined);api.getCompensationExecutionPreview.mockResolvedValue(structuredClone(executionPreview));api.approveCompensationDraft.mockResolvedValue(undefined);api.updateCompensationExecutionEnabled.mockResolvedValue(undefined);api.executeCompensationDraft.mockResolvedValue({draft_id:10,approval_id:9,state:'verified',verified_count:2,failed_count:0,notices_created:1,executions:[]});api.refundErroneousCharge.mockResolvedValue(undefined);api.generateCompensationDraft.mockResolvedValue(structuredClone(draft));api.reviewCompensationDraft.mockResolvedValue(undefined);api.reviseCompensationDraft.mockResolvedValue({...structuredClone(draft),id:11,revision_number:2,proposed_total_cny_fen:2000})})
describe('CompensationShadowView',()=>{
  it('renders explanation-first formula, exact notice preview, and explicitly gated execution controls',async()=>{const wrapper=mountView();await flushPromises();expect(wrapper.text()).toContain('2 / 30');expect(wrapper.text()).toContain('1 / 0');await wrapper.get('[data-test="draft-row"]').trigger('click');await flushPromises();expect(wrapper.text()).toContain('customer@example.com');expect(wrapper.text()).toContain('最终失败 4 次');expect(wrapper.text()).toContain('¥30.00/h × 1.00 × 1.25');expect(wrapper.text()).toContain('余额 ¥6.00');expect(wrapper.text()).toContain('Builder Pass ¥24.00');expect(wrapper.text()).toContain('执行前逐用户通知原文预览');expect(wrapper.text()).toContain(executionPreview.notice_previews[0].body);expect(wrapper.text()).toContain('显式审批与可恢复执行');expect(wrapper.get('[aria-label="审批确认短语"]').element).toHaveProperty('value','');expect(wrapper.get('[aria-label="执行启用确认短语"]').element).toHaveProperty('value','')})
  it('creates an immutable reasoned revision',async()=>{const wrapper=mountView();await flushPromises();await wrapper.get('[data-test="draft-row"]').trigger('click');await flushPromises();await wrapper.get('[aria-label="修订原因"]').setValue('conservative owner redesign');await wrapper.get('[aria-label="User 7 修订金额"]').setValue(2000);await wrapper.findAll('button').find(button=>button.text().includes('创建新 Revision'))!.trigger('click');await flushPromises();expect(api.reviseCompensationDraft).toHaveBeenCalledWith(10,'conservative owner redesign',[{user_id:7,included:true,proposed_cny_fen:2000}])})
  it('records an immutable shadow comparison without approving execution',async()=>{const wrapper=mountView();await flushPromises();await wrapper.get('[data-test="draft-row"]').trigger('click');await flushPromises();await wrapper.get('[aria-label="Owner 判断金额"]').setValue(2800);await wrapper.get('[aria-label="复核说明"]').setValue('owner incident comparison');await wrapper.findAll('button').find(button=>button.text().includes('保存不可变复核'))!.trigger('click');await flushPromises();expect(api.reviewCompensationDraft).toHaveBeenCalledWith(10,2800,'aligned','owner incident comparison')})
  it('does not commit a pending generated draft after unmount',async()=>{const wrapper=mountView();await flushPromises();let resolve!: (value:typeof draft)=>void;api.generateCompensationDraft.mockImplementationOnce(()=>new Promise(r=>{resolve=r}));await wrapper.get('[aria-label="Incident ID"]').setValue(5);await wrapper.findAll('button').find(button=>button.text().includes('生成/读取'))!.trigger('click');await flushPromises();wrapper.unmount();resolve(structuredClone(draft));await flushPromises();expect(api.getCompensationSnapshot).toHaveBeenCalledTimes(1);expect(api.getCompensationDraft).not.toHaveBeenCalled()})
  it('does not commit a pending revision after unmount',async()=>{const wrapper=mountView();await flushPromises();await wrapper.get('[data-test="draft-row"]').trigger('click');await flushPromises();let resolve!: (value:typeof draft)=>void;api.reviseCompensationDraft.mockImplementationOnce(()=>new Promise(r=>{resolve=r}));await wrapper.get('[aria-label="修订原因"]').setValue('pending revision');await wrapper.get('[aria-label="User 7 修订金额"]').setValue(2000);await wrapper.findAll('button').find(button=>button.text().includes('创建新 Revision'))!.trigger('click');await flushPromises();wrapper.unmount();resolve({...structuredClone(draft),id:11,revision_number:2});await flushPromises();expect(api.getCompensationSnapshot).toHaveBeenCalledTimes(1);expect(api.getCompensationDraft).toHaveBeenCalledTimes(1)})
  it('requires typed owner phrases and the viewed preview hash before approval and execution',async()=>{const wrapper=mountView();await flushPromises();await wrapper.get('[data-test="draft-row"]').trigger('click');await flushPromises();await wrapper.get('[aria-label="审批幂等键"]').setValue('approval-1');await wrapper.get('[aria-label="审批原因"]').setValue('owner approved');await wrapper.get('[aria-label="审批确认短语"]').setValue('I_APPROVE_THIS_COMPENSATION_DRAFT');await wrapper.findAll('button').find(button=>button.text().includes('写入不可变审批'))!.trigger('click');await flushPromises();expect(api.approveCompensationDraft).toHaveBeenCalledWith(10,'approval-1','owner approved','I_APPROVE_THIS_COMPENSATION_DRAFT',executionPreview.approval_preview_hash);await wrapper.get('[aria-label="执行启用确认短语"]').setValue('I_ENABLE_COMPENSATION_EXECUTION');await wrapper.findAll('button').find(button=>button.text().includes('显式开启执行权限'))!.trigger('click');await flushPromises();expect(api.updateCompensationExecutionEnabled).toHaveBeenCalledWith(true,'I_ENABLE_COMPENSATION_EXECUTION');await wrapper.findAll('button').find(button=>button.text().includes('执行 / 恢复'))!.trigger('click');await flushPromises();expect(api.executeCompensationDraft).toHaveBeenCalledWith(10)})
  it('clears all high-risk inputs when switching drafts',async()=>{api.getCompensationSnapshot.mockResolvedValueOnce({...structuredClone(snapshot),drafts:[{...structuredClone(draft),users:undefined},{...structuredClone(draft),id:11,incident_id:6,users:undefined}]});const wrapper=mountView();await flushPromises();await wrapper.findAll('[data-test="draft-row"]')[0].trigger('click');await flushPromises();await wrapper.get('[aria-label="审批幂等键"]').setValue('approval-old');await wrapper.get('[aria-label="审批原因"]').setValue('old draft');await wrapper.get('[aria-label="审批确认短语"]').setValue('I_APPROVE_THIS_COMPENSATION_DRAFT');await wrapper.get('[aria-label="执行启用确认短语"]').setValue('I_ENABLE_COMPENSATION_EXECUTION');await wrapper.get('[aria-label="退款幂等键"]').setValue('refund-old');api.getCompensationDraft.mockResolvedValueOnce({...structuredClone(draft),id:11,incident_id:6});api.getCompensationExecutionPreview.mockResolvedValueOnce({...structuredClone(executionPreview),draft_id:11});await wrapper.findAll('[data-test="draft-row"]')[1].trigger('click');await flushPromises();expect((wrapper.get('[aria-label="审批幂等键"]').element as HTMLInputElement).value).toBe('');expect((wrapper.get('[aria-label="审批原因"]').element as HTMLInputElement).value).toBe('');expect((wrapper.get('[aria-label="审批确认短语"]').element as HTMLInputElement).value).toBe('');expect((wrapper.get('[aria-label="执行启用确认短语"]').element as HTMLInputElement).value).toBe('');expect((wrapper.get('[aria-label="退款幂等键"]').element as HTMLInputElement).value).toBe('')})
  it('submits erroneous-charge refunds through the separate exact path',async()=>{const wrapper=mountView();await flushPromises();await wrapper.get('[data-test="draft-row"]').trigger('click');await flushPromises();await wrapper.get('[aria-label="退款用户 ID"]').setValue(7);await wrapper.get('[aria-label="Usage Log ID"]').setValue(99);await wrapper.get('[aria-label="退款幂等键"]').setValue('refund-99');await wrapper.get('[aria-label="退款原因"]').setValue('verified wrong charge');await wrapper.findAll('button').find(button=>button.text().includes('精确退款'))!.trigger('click');await flushPromises();expect(api.refundErroneousCharge).toHaveBeenCalledWith({idempotency_key:'refund-99',usage_log_id:99,user_id:7,reason:'verified wrong charge'})})
})
