// Code generated by scripts/model_catalog.py; DO NOT EDIT.

package service

import "strings"

type generatedCatalogGroupPolicy struct {
	Preferred string
	Legacy    []string
}

var generatedCatalogBillingPrices = map[string]*ModelPricing{
	"grok-4.6": {InputPricePerToken: 2e-6, OutputPricePerToken: 6e-6, CacheReadPricePerToken: 0.5e-6, LongContextInputThreshold: 200000, LongContextInputMultiplier: 2, LongContextOutputMultiplier: 2},
}

var generatedCatalogDisplayPrices = map[string]manualOfficialPrice{
	"grok-4.6": {input: 2, output: 6, cacheRead: 0.5},
}

var generatedCatalogClientDefaults = map[string]string{
	"grok": "grok-4.6",
}

var generatedCatalogGroupPolicies = map[string]generatedCatalogGroupPolicy{
	"grok": {Preferred: "Grok 4.6", Legacy: []string{"Grok 4.5"}},
}

func generatedCatalogBillingPrice(model string) *ModelPricing {
	return generatedCatalogBillingPrices[strings.ToLower(strings.TrimSpace(model))]
}

func generatedCatalogClientDefault(platform string) string {
	return generatedCatalogClientDefaults[strings.ToLower(strings.TrimSpace(platform))]
}

func generatedCatalogGroupPolicyFor(platform string) generatedCatalogGroupPolicy {
	return generatedCatalogGroupPolicies[strings.ToLower(strings.TrimSpace(platform))]
}
