// Code generated by ent, DO NOT EDIT.

package commissionrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldID, id))
}

// BeneficiaryID applies equality check predicate on the "beneficiary_id" field. It's identical to BeneficiaryIDEQ.
func BeneficiaryID(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldBeneficiaryID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldAmount, v))
}

// SourceAmount applies equality check predicate on the "source_amount" field. It's identical to SourceAmountEQ.
func SourceAmount(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldSourceAmount, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldSourceID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// BeneficiaryIDEQ applies the EQ predicate on the "beneficiary_id" field.
func BeneficiaryIDEQ(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldBeneficiaryID, v))
}

// BeneficiaryIDNEQ applies the NEQ predicate on the "beneficiary_id" field.
func BeneficiaryIDNEQ(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldBeneficiaryID, v))
}

// BeneficiaryIDIn applies the In predicate on the "beneficiary_id" field.
func BeneficiaryIDIn(vs ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldBeneficiaryID, vs...))
}

// BeneficiaryIDNotIn applies the NotIn predicate on the "beneficiary_id" field.
func BeneficiaryIDNotIn(vs ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldBeneficiaryID, vs...))
}

// BeneficiaryIDGT applies the GT predicate on the "beneficiary_id" field.
func BeneficiaryIDGT(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldBeneficiaryID, v))
}

// BeneficiaryIDGTE applies the GTE predicate on the "beneficiary_id" field.
func BeneficiaryIDGTE(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldBeneficiaryID, v))
}

// BeneficiaryIDLT applies the LT predicate on the "beneficiary_id" field.
func BeneficiaryIDLT(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldBeneficiaryID, v))
}

// BeneficiaryIDLTE applies the LTE predicate on the "beneficiary_id" field.
func BeneficiaryIDLTE(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldBeneficiaryID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldUserID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldAmount, v))
}

// SourceAmountEQ applies the EQ predicate on the "source_amount" field.
func SourceAmountEQ(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldSourceAmount, v))
}

// SourceAmountNEQ applies the NEQ predicate on the "source_amount" field.
func SourceAmountNEQ(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldSourceAmount, v))
}

// SourceAmountIn applies the In predicate on the "source_amount" field.
func SourceAmountIn(vs ...float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldSourceAmount, vs...))
}

// SourceAmountNotIn applies the NotIn predicate on the "source_amount" field.
func SourceAmountNotIn(vs ...float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldSourceAmount, vs...))
}

// SourceAmountGT applies the GT predicate on the "source_amount" field.
func SourceAmountGT(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldSourceAmount, v))
}

// SourceAmountGTE applies the GTE predicate on the "source_amount" field.
func SourceAmountGTE(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldSourceAmount, v))
}

// SourceAmountLT applies the LT predicate on the "source_amount" field.
func SourceAmountLT(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldSourceAmount, v))
}

// SourceAmountLTE applies the LTE predicate on the "source_amount" field.
func SourceAmountLTE(v float64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldSourceAmount, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldContainsFold(FieldType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotNull(FieldSourceID))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommissionRecord) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommissionRecord) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommissionRecord) predicate.CommissionRecord {
	return predicate.CommissionRecord(sql.NotPredicates(p))
}
