import { apiClient } from '@/api/client'
export type CompensationTier='standard'|'priority'|'strategic'
export interface CompensationItem { id:number;user_id:number;product_id:number;product_name?:string;group_id?:number;group_name?:string;benefit_channel:'balance'|'builder_pass';first_qualifying_failure_at:string;compensable_duration_ms:number;product_rate_cny_fen_per_hour:number;group_weight_bps:number;tier_multiplier_bps:number;raw_value_cny_micros:number;proposed_cny_fen:number;exclusion_reason?:string }
export interface CompensationUser { id:number;user_id:number;email?:string;tier:CompensationTier;eligible:boolean;included:boolean;final_failure_count:number;first_qualifying_failure_at?:string;verified_paid_value_cny_fen:number;raw_value_cny_micros:number;tier_cap_cny_fen:number;relationship_cap_cny_fen:number;rolling_cap_cny_fen?:number;rolling_remaining_cny_fen?:number;proposed_total_cny_fen:number;balance_benefit_cny_fen:number;builder_pass_benefit_cny_fen:number;limiting_cap:string;exclusion_reason?:string;items:CompensationItem[] }
export interface CompensationDraft { id:number;series_id:string;incident_id:number;policy_version:number;revision_number:number;replaces_draft_id?:number;state:'shadow'|'redesign_required';revision_reason?:string;redesigned:boolean;eligible_user_count:number;affected_user_count:number;proposed_total_cny_fen:number;affected_product_rolling_paid_value_cny_fen:number;high_value_threshold_cny_fen:number;high_value:boolean;evidence_hash:string;created_at:string;users?:CompensationUser[];review?:{id:number;owner_judgement_total_cny_fen:number;variance_cny_fen:number;result:string;notes:string;created_at:string} }
export interface CompensationSnapshot { enabled:boolean;generated_at:string;assessment:{enabled:boolean;started_at?:string;elapsed_days:number;evaluated_incident_count:number;reviewed_incident_count:number;evidence_complete:boolean;minimum_days:number;minimum_incidents:number;eligible_for_owner_review:boolean;execution_available:boolean};drafts:CompensationDraft[] }
export interface CompensationAdjustment { user_id:number;included:boolean;proposed_cny_fen:number }
export async function getCompensationSnapshot(signal?:AbortSignal){const r=await apiClient.get<CompensationSnapshot>('/admin/ops/compensation',{signal});return r.data}
export async function getCompensationDraft(id:number,signal?:AbortSignal){const r=await apiClient.get<CompensationDraft>(`/admin/ops/compensation/drafts/${id}`,{signal});return r.data}
export async function updateCompensationShadow(enabled:boolean){await apiClient.put('/admin/ops/compensation/settings',{enabled})}
export async function generateCompensationDraft(incidentId:number){const r=await apiClient.post<CompensationDraft>(`/admin/ops/compensation/incidents/${incidentId}/draft`);return r.data}
export async function reviseCompensationDraft(id:number,reason:string,adjustments:CompensationAdjustment[]){const r=await apiClient.post<CompensationDraft>(`/admin/ops/compensation/drafts/${id}/revisions`,{reason,adjustments});return r.data}
export async function reviewCompensationDraft(id:number,ownerJudgementTotalCNYFen:number,result:string,notes:string){await apiClient.post(`/admin/ops/compensation/drafts/${id}/reviews`,{owner_judgement_total_cny_fen:ownerJudgementTotalCNYFen,result,notes})}
