import { apiClient } from '@/api/client'
export type CompensationTier='standard'|'priority'|'strategic'
export interface CompensationItem { id:number;user_id:number;product_id:number;product_name?:string;group_id?:number;group_name?:string;benefit_channel:'balance'|'builder_pass';first_qualifying_failure_at:string;compensable_duration_ms:number;product_rate_cny_fen_per_hour:number;group_weight_bps:number;tier_multiplier_bps:number;raw_value_cny_micros:number;proposed_cny_fen:number;exclusion_reason?:string }
export interface CompensationUser { id:number;user_id:number;email?:string;tier:CompensationTier;eligible:boolean;included:boolean;final_failure_count:number;first_qualifying_failure_at?:string;verified_paid_value_cny_fen:number;raw_value_cny_micros:number;tier_cap_cny_fen:number;relationship_cap_cny_fen:number;rolling_cap_cny_fen?:number;rolling_remaining_cny_fen?:number;proposed_total_cny_fen:number;balance_benefit_cny_fen:number;builder_pass_benefit_cny_fen:number;limiting_cap:string;exclusion_reason?:string;items:CompensationItem[] }
export interface CompensationDraft { id:number;series_id:string;incident_id:number;policy_version:number;revision_number:number;replaces_draft_id?:number;state:'shadow'|'redesign_required';revision_reason?:string;redesigned:boolean;eligible_user_count:number;affected_user_count:number;proposed_total_cny_fen:number;affected_product_rolling_paid_value_cny_fen:number;high_value_threshold_cny_fen:number;high_value:boolean;evidence_hash:string;created_at:string;users?:CompensationUser[];review?:{id:number;owner_judgement_total_cny_fen:number;variance_cny_fen:number;result:string;notes:string;created_at:string} }
export interface CompensationSnapshot { enabled:boolean;generated_at:string;assessment:{enabled:boolean;started_at?:string;elapsed_days:number;evaluated_incident_count:number;reviewed_incident_count:number;evidence_complete:boolean;minimum_days:number;minimum_incidents:number;eligible_for_owner_review:boolean;execution_available:boolean};drafts:CompensationDraft[] }
export interface CompensationAdjustment { user_id:number;included:boolean;proposed_cny_fen:number }
export interface CompensationExecutionPreview { draft_id:number;latest:boolean;incident_resolved:boolean;shadow_gate_eligible:boolean;execution_enabled:boolean;approval_id?:number;total_cny_fen:number;balance_cny_fen:number;builder_pass_cny_fen:number;user_count:number;executable:boolean;blockers:string[];notice_previews:Array<{user_id:number;services:string[];balance_cny_fen:number;builder_pass_cny_fen:number;failed_requests_charged:boolean;body:string}>;approval_preview_hash:string }
export interface CompensationExecutionBatch { draft_id:number;approval_id:number;state:'partial'|'verified';verified_count:number;failed_count:number;notices_created:number;executions:Array<{id:number;user_id:number;benefit_channel:'balance'|'builder_pass';amount_cny_fen:number;state:string;attempt_count:number;last_error?:string}> }
export async function getCompensationSnapshot(signal?:AbortSignal){const r=await apiClient.get<CompensationSnapshot>('/admin/ops/compensation',{signal});return r.data}
export async function getCompensationDraft(id:number,signal?:AbortSignal){const r=await apiClient.get<CompensationDraft>(`/admin/ops/compensation/drafts/${id}`,{signal});return r.data}
export async function updateCompensationShadow(enabled:boolean){await apiClient.put('/admin/ops/compensation/settings',{enabled})}
export async function generateCompensationDraft(incidentId:number){const r=await apiClient.post<CompensationDraft>(`/admin/ops/compensation/incidents/${incidentId}/draft`);return r.data}
export async function reviseCompensationDraft(id:number,reason:string,adjustments:CompensationAdjustment[]){const r=await apiClient.post<CompensationDraft>(`/admin/ops/compensation/drafts/${id}/revisions`,{reason,adjustments});return r.data}
export async function reviewCompensationDraft(id:number,ownerJudgementTotalCNYFen:number,result:string,notes:string){await apiClient.post(`/admin/ops/compensation/drafts/${id}/reviews`,{owner_judgement_total_cny_fen:ownerJudgementTotalCNYFen,result,notes})}
export async function getCompensationExecutionPreview(id:number,signal?:AbortSignal){const r=await apiClient.get<CompensationExecutionPreview>(`/admin/ops/compensation/drafts/${id}/execution-preview`,{signal});return r.data}
export async function approveCompensationDraft(id:number,approvalKey:string,reason:string,confirmation:string,previewHash:string){await apiClient.post(`/admin/ops/compensation/drafts/${id}/approve`,{approval_key:approvalKey,reason,confirmation,preview_hash:previewHash})}
export async function updateCompensationExecutionEnabled(enabled:boolean,confirmation:string){await apiClient.put('/admin/ops/compensation/execution-settings',{enabled,confirmation})}
export async function executeCompensationDraft(id:number){try{const r=await apiClient.post<CompensationExecutionBatch>(`/admin/ops/compensation/drafts/${id}/execute`);return r.data}catch(cause:unknown){const partial=(cause as {response?:{data?:{data?:CompensationExecutionBatch}}}).response?.data?.data;if(partial?.state==='partial')return partial;throw cause}}
export async function refundErroneousCharge(payload:{idempotency_key:string;usage_log_id:number;user_id:number;reason:string}){await apiClient.post('/admin/ops/compensation/erroneous-charge-refunds',payload)}
