import { apiClient } from '@/api/client'

export type CustomerTier = 'standard' | 'priority' | 'strategic'
export interface CustomerTierCurrent { user_id: number; email?: string; calculated_tier: CustomerTier; effective_tier: CustomerTier; verified_paid_value_cny_fen: number; verified_paid_consumption_micros: number; grace_expires_at?: string; override_id?: number; last_evaluation_id: number; evaluated_at: string; projection_status?: string }
export interface CustomerTierSnapshot { enabled: boolean; generated_at: string; customers: CustomerTierCurrent[]; page: number; page_size: number; total: number }
export interface CustomerTierEvidenceItem { source_type: string; source_id: number; gross_amount_cny_fen: number; refunded_amount_cny_fen: number; amount_cny_fen: number; occurred_at: string; included: boolean; exclusion_reason?: string }
export interface CustomerTierEvaluation { id: number; policy_version: number; calculated_tier: CustomerTier; effective_tier: CustomerTier; resolution_reason: string; verified_paid_value_cny_fen: number; verified_paid_consumption_micros: number; evidence_hash: string; evaluated_at: string; evidence: { window_started_at: string; window_ended_at: string; paid_sources: CustomerTierEvidenceItem[]; balance_paid_consumption_micros: number; builder_pass_consumption_micros: number; verified_paid_consumption_micros: number } }
export interface CustomerTierExplanation { current: CustomerTierCurrent; evaluation: CustomerTierEvaluation; history: Array<{ id: number; previous_tier?: CustomerTier; new_tier: CustomerTier; change_reason: string; changed_at: string }>; overrides: Array<{ id: number; tier: CustomerTier; reason: string; starts_at: string; expires_at: string; created_by_user_id?: number; created_at: string; refresh_status: string; refresh_error?: string }>; benefit: { multiplier: number; cap_cny_fen: number } }

export async function getCustomerTiers(signal?: AbortSignal, params?: { page?: number; page_size?: number; search?: string; tier?: CustomerTier | '' }) { const response = await apiClient.get<CustomerTierSnapshot>('/admin/ops/customer-tiers', { signal, params }); return response.data }
export async function getCustomerTierUser(userId: number, signal?: AbortSignal) { const response = await apiClient.get<CustomerTierExplanation>(`/admin/ops/customer-tiers/users/${userId}`, { signal }); return response.data }
export async function updateCustomerTierSettings(enabled: boolean) { await apiClient.put('/admin/ops/customer-tiers/settings', { enabled }) }
export async function createCustomerTierOverride(userId: number, tier: CustomerTier, reason: string, durationDays: number) { await apiClient.post(`/admin/ops/customer-tiers/users/${userId}/overrides`, { tier, reason, duration_days: durationDays }) }
