// Code generated by ent, DO NOT EDIT.

package financetransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bozhouDev/DragonCode-sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldType, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldCategory, v))
}

// AmountFen applies equality check predicate on the "amount_fen" field. It's identical to AmountFenEQ.
func AmountFen(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldAmountFen, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldOccurredAt, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldNote, v))
}

// ReceiptKey applies equality check predicate on the "receipt_key" field. It's identical to ReceiptKeyEQ.
func ReceiptKey(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldReceiptKey, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldSource, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContainsFold(FieldType, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContainsFold(FieldCategory, v))
}

// AmountFenEQ applies the EQ predicate on the "amount_fen" field.
func AmountFenEQ(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldAmountFen, v))
}

// AmountFenNEQ applies the NEQ predicate on the "amount_fen" field.
func AmountFenNEQ(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldAmountFen, v))
}

// AmountFenIn applies the In predicate on the "amount_fen" field.
func AmountFenIn(vs ...int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldAmountFen, vs...))
}

// AmountFenNotIn applies the NotIn predicate on the "amount_fen" field.
func AmountFenNotIn(vs ...int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldAmountFen, vs...))
}

// AmountFenGT applies the GT predicate on the "amount_fen" field.
func AmountFenGT(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldAmountFen, v))
}

// AmountFenGTE applies the GTE predicate on the "amount_fen" field.
func AmountFenGTE(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldAmountFen, v))
}

// AmountFenLT applies the LT predicate on the "amount_fen" field.
func AmountFenLT(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldAmountFen, v))
}

// AmountFenLTE applies the LTE predicate on the "amount_fen" field.
func AmountFenLTE(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldAmountFen, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldOccurredAt, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContainsFold(FieldNote, v))
}

// ReceiptKeyEQ applies the EQ predicate on the "receipt_key" field.
func ReceiptKeyEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldReceiptKey, v))
}

// ReceiptKeyNEQ applies the NEQ predicate on the "receipt_key" field.
func ReceiptKeyNEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldReceiptKey, v))
}

// ReceiptKeyIn applies the In predicate on the "receipt_key" field.
func ReceiptKeyIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldReceiptKey, vs...))
}

// ReceiptKeyNotIn applies the NotIn predicate on the "receipt_key" field.
func ReceiptKeyNotIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldReceiptKey, vs...))
}

// ReceiptKeyGT applies the GT predicate on the "receipt_key" field.
func ReceiptKeyGT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldReceiptKey, v))
}

// ReceiptKeyGTE applies the GTE predicate on the "receipt_key" field.
func ReceiptKeyGTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldReceiptKey, v))
}

// ReceiptKeyLT applies the LT predicate on the "receipt_key" field.
func ReceiptKeyLT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldReceiptKey, v))
}

// ReceiptKeyLTE applies the LTE predicate on the "receipt_key" field.
func ReceiptKeyLTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldReceiptKey, v))
}

// ReceiptKeyContains applies the Contains predicate on the "receipt_key" field.
func ReceiptKeyContains(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContains(FieldReceiptKey, v))
}

// ReceiptKeyHasPrefix applies the HasPrefix predicate on the "receipt_key" field.
func ReceiptKeyHasPrefix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasPrefix(FieldReceiptKey, v))
}

// ReceiptKeyHasSuffix applies the HasSuffix predicate on the "receipt_key" field.
func ReceiptKeyHasSuffix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasSuffix(FieldReceiptKey, v))
}

// ReceiptKeyIsNil applies the IsNil predicate on the "receipt_key" field.
func ReceiptKeyIsNil() predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIsNull(FieldReceiptKey))
}

// ReceiptKeyNotNil applies the NotNil predicate on the "receipt_key" field.
func ReceiptKeyNotNil() predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotNull(FieldReceiptKey))
}

// ReceiptKeyEqualFold applies the EqualFold predicate on the "receipt_key" field.
func ReceiptKeyEqualFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEqualFold(FieldReceiptKey, v))
}

// ReceiptKeyContainsFold applies the ContainsFold predicate on the "receipt_key" field.
func ReceiptKeyContainsFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContainsFold(FieldReceiptKey, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldContainsFold(FieldSource, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FinanceTransaction) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FinanceTransaction) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FinanceTransaction) predicate.FinanceTransaction {
	return predicate.FinanceTransaction(sql.NotPredicates(p))
}
